//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.29 at 06:09:43 PM IST 
//

package com.lca.ddt.delivery.report.inspire.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for commentType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="commentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="text" type="{}advancedStringType" minOccurs="0"/>
 *         &lt;element name="sequence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="forceBold" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "commentType", propOrder = { "name", "text", "sequence", "forceBold" })
public class CommentType {

	protected String name;
	protected AdvancedStringType text;
	protected String sequence;
	protected Boolean forceBold;

	public CommentType() {
		// empty
	}

	public CommentType(String name, AdvancedStringType text) {
		this.name = name;
		this.text = text;
	}
	
	public CommentType(AdvancedStringType text) {
		this.text = text;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the text property.
	 * 
	 * @return possible object is {@link AdvancedStringType }
	 * 
	 */
	public AdvancedStringType getText() {
		return text;
	}

	/**
	 * Sets the value of the text property.
	 * 
	 * @param value
	 *            allowed object is {@link AdvancedStringType }
	 * 
	 */
	public void setText(AdvancedStringType value) {
		this.text = value;
	}

	/**
	 * Gets the value of the sequence property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSequence() {
		return sequence;
	}

	/**
	 * Sets the value of the sequence property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSequence(String value) {
		this.sequence = value;
	}

	/**
	 * Gets the value of the forceBold property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isForceBold() {
		return forceBold;
	}

	/**
	 * Sets the value of the forceBold property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setForceBold(Boolean value) {
		this.forceBold = value;
	}

}
