//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.29 at 06:09:43 PM IST 
//

package com.lca.ddt.delivery.report.inspire.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for nameType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="nameType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="first" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="middle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="last" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nameType", propOrder = { "first", "middle", "last", "suffix", "title" })
public class NameType {

	protected String first;
	protected String middle;
	@XmlElement(required = true)
	protected AdvancedStringType last;
	protected String suffix;
	protected String title;

	public NameType() {
		// empty
	}

	public NameType(String first, String middle, AdvancedStringType last) {
		this.first = first;
		this.middle = middle;
		this.last = last;
	}

	/**
	 * Gets the value of the first property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFirst() {
		return first;
	}

	/**
	 * Sets the value of the first property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setFirst(String value) {
		this.first = value;
	}

	/**
	 * Gets the value of the middle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMiddle() {
		return middle;
	}

	/**
	 * Sets the value of the middle property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setMiddle(String value) {
		this.middle = value;
	}

	/**
	 * Gets the value of the last property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public AdvancedStringType getLast() {
		return last;
	}

	/**
	 * Sets the value of the last property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setLast(AdvancedStringType value) {
		this.last = value;
	}

	/**
	 * Gets the value of the suffix property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSuffix() {
		return suffix;
	}

	/**
	 * Sets the value of the suffix property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setSuffix(String value) {
		this.suffix = value;
	}

	/**
	 * Gets the value of the title property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTitle(String value) {
		this.title = value;
	}

}
