//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.29 at 06:09:43 PM IST 
//


package com.lca.ddt.delivery.report.inspire.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.labcorp.erg.response.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.labcorp.erg.response.model
     * 
     */
    public ObjectFactory() {
    	//empty
    }

    /**
     * Create an instance of {@link Inspire }
     * 
     */
    public Inspire createInspire() {
        return new Inspire();
    }

    /**
     * Create an instance of {@link ResultType }
     * 
     */
    public ResultType createResultType() {
        return new ResultType();
    }

    /**
     * Create an instance of {@link LabType }
     * 
     */
    public LabType createLabType() {
        return new LabType();
    }

    /**
     * Create an instance of {@link PatientType }
     * 
     */
    public PatientType createPatientType() {
        return new PatientType();
    }

    /**
     * Create an instance of {@link Inspire.Accessions }
     * 
     */
    public Inspire.Accessions createInspireAccessions() {
        return new Inspire.Accessions();
    }

    /**
     * Create an instance of {@link PhysicianType }
     * 
     */
    public PhysicianType createPhysicianType() {
        return new PhysicianType();
    }

    /**
     * Create an instance of {@link OrderType }
     * 
     */
    public OrderType createOrderType() {
        return new OrderType();
    }

    /**
     * Create an instance of {@link OrderItemType }
     * 
     */
    public OrderItemType createOrderItemType() {
        return new OrderItemType();
    }

    /**
     * Create an instance of {@link SpecialtyType }
     * 
     */
    public SpecialtyType createSpecialtyType() {
        return new SpecialtyType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link AccountType }
     * 
     */
    public AccountType createAccountType() {
        return new AccountType();
    }

    /**
     * Create an instance of {@link SignedByType }
     * 
     */
    public SignedByType createSignedByType() {
        return new SignedByType();
    }

    /**
     * Create an instance of {@link MarkerType }
     * 
     */
    public MarkerType createMarkerType() {
        return new MarkerType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link ReportType }
     * 
     */
    public ReportType createReportType() {
        return new ReportType();
    }

    /**
     * Create an instance of {@link FixativeType }
     * 
     */
    public FixativeType createFixativeType() {
        return new FixativeType();
    }

    /**
     * Create an instance of {@link KeyValuePairType }
     * 
     */
    public KeyValuePairType createKeyValuePairType() {
        return new KeyValuePairType();
    }

    /**
     * Create an instance of {@link CommentType }
     * 
     */
    public CommentType createCommentType() {
        return new CommentType();
    }

    /**
     * Create an instance of {@link SpecimenType }
     * 
     */
    public SpecimenType createSpecimenType() {
        return new SpecimenType();
    }

    /**
     * Create an instance of {@link ImageType }
     * 
     */
    public ImageType createImageType() {
        return new ImageType();
    }

    /**
     * Create an instance of {@link AdvancedStringType }
     * 
     */
    public AdvancedStringType createAdvancedStringType() {
        return new AdvancedStringType();
    }

    /**
     * Create an instance of {@link ResultType.ReferenceRange }
     * 
     */
    public ResultType.ReferenceRange createResultTypeReferenceRange() {
        return new ResultType.ReferenceRange();
    }

    /**
     * Create an instance of {@link LabType.Director }
     * 
     */
    public LabType.Director createLabTypeDirector() {
        return new LabType.Director();
    }

    /**
     * Create an instance of {@link PatientType.Age }
     * 
     */
    public PatientType.Age createPatientTypeAge() {
        return new PatientType.Age();
    }

    /**
     * Create an instance of {@link PatientType.Height }
     * 
     */
    public PatientType.Height createPatientTypeHeight() {
        return new PatientType.Height();
    }

    /**
     * Create an instance of {@link PatientType.Weight }
     * 
     */
    public PatientType.Weight createPatientTypeWeight() {
        return new PatientType.Weight();
    }

    /**
     * Create an instance of {@link Inspire.Accessions.PreviousEncounters }
     * 
     */
    public Inspire.Accessions.PreviousEncounters createInspireAccessionsPreviousEncounters() {
        return new Inspire.Accessions.PreviousEncounters();
    }

}
