//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.29 at 06:09:43 PM IST 
//

package com.lca.ddt.delivery.report.inspire.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for orderType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="orderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="caseId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="forcePageBreak" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="revision" type="{}commentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="signedBy" type="{}signedByType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalResults" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Disclaimers" type="{}commentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AttachedImages" type="{}imageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Comments" type="{}commentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Results" type="{}resultType" maxOccurs="unbounded"/>
 *         &lt;element name="Specimens" type="{}specimenType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="referenceLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="blockNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderType", propOrder = { "number", "name", "caseId", "forcePageBreak", "revision", "signedBy",
		"status", "totalResults", "disclaimers", "attachedImages", "comments", "results", "specimens", "referenceLevel",
		"blockNumber" })
public class OrderType {

	protected String number;
	@XmlElement(required = true)
	protected String name;
	protected String caseId;
	protected Boolean forcePageBreak;
	protected List<CommentType> revision;
	protected List<SignedByType> signedBy;
	@XmlElement(required = true)
	protected String status;
	protected String totalResults;
	@XmlElement(name = "Disclaimers")
	protected List<CommentType> disclaimers;
	@XmlElement(name = "AttachedImages")
	protected List<ImageType> attachedImages;
	@XmlElement(name = "Comments")
	protected List<CommentType> comments;
	@XmlElement(name = "Results", required = true)
	protected List<ResultType> results;
	@XmlElement(name = "Specimens")
	protected List<SpecimenType> specimens;
	protected String referenceLevel;
	protected String blockNumber;

	public OrderType() {
		// empty
	}

	public OrderType(String name, String status) {
		this.name = name;
		this.status = status;
	}

	/**
	 * Gets the value of the number property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNumber() {
		return number;
	}

	/**
	 * Sets the value of the number property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setNumber(String value) {
		this.number = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the caseId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCaseId() {
		return caseId;
	}

	/**
	 * Sets the value of the caseId property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCaseId(String value) {
		this.caseId = value;
	}

	/**
	 * Gets the value of the forcePageBreak property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isForcePageBreak() {
		return forcePageBreak;
	}

	/**
	 * Sets the value of the forcePageBreak property.
	 * 
	 * @param value allowed object is {@link Boolean }
	 * 
	 */
	public void setForcePageBreak(Boolean value) {
		this.forcePageBreak = value;
	}

	/**
	 * Gets the value of the revision property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the revision property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRevision().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link CommentType }
	 * 
	 * 
	 */
	public List<CommentType> getRevision() {
		if (revision == null) {
			revision = new ArrayList<>();
		}
		return this.revision;
	}

	/**
	 * Gets the value of the signedBy property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the signedBy property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSignedBy().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link SignedByType
	 * }
	 * 
	 * 
	 */
	public List<SignedByType> getSignedBy() {
		if (signedBy == null) {
			signedBy = new ArrayList<>();
		}
		return this.signedBy;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStatus(String value) {
		this.status = value;
	}

	/**
	 * Gets the value of the totalResults property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTotalResults() {
		return totalResults;
	}

	/**
	 * Sets the value of the totalResults property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTotalResults(String value) {
		this.totalResults = value;
	}

	/**
	 * Gets the value of the disclaimers property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the disclaimers property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDisclaimers().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link CommentType }
	 * 
	 * 
	 */
	public List<CommentType> getDisclaimers() {
		if (disclaimers == null) {
			disclaimers = new ArrayList<>();
		}
		return this.disclaimers;
	}

	/**
	 * Gets the value of the attachedImages property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the attachedImages property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAttachedImages().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link ImageType }
	 * 
	 * 
	 */
	public List<ImageType> getAttachedImages() {
		if (attachedImages == null) {
			attachedImages = new ArrayList<>();
		}
		return this.attachedImages;
	}

	/**
	 * Gets the value of the comments property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the comments property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getComments().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link CommentType }
	 * 
	 * 
	 */
	public List<CommentType> getComments() {
		if (comments == null) {
			comments = new ArrayList<>();
		}
		return this.comments;
	}

	/**
	 * Gets the value of the results property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the results property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getResults().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link ResultType }
	 * 
	 * 
	 */
	public List<ResultType> getResults() {
		if (results == null) {
			results = new ArrayList<>();
		}
		return this.results;
	}

	public OrderType addResult(ResultType result) {
		if (results == null) {
			results = new ArrayList<>();
		}
		this.results.add(result);
		return this;
	}

	/**
	 * Gets the value of the specimens property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the specimens property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSpecimens().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link SpecimenType
	 * }
	 * 
	 * 
	 */
	public List<SpecimenType> getSpecimens() {
		if (specimens == null) {
			specimens = new ArrayList<>();
		}
		return this.specimens;
	}

	/**
	 * Gets the value of the referenceLevel property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReferenceLevel() {
		return referenceLevel;
	}

	/**
	 * Sets the value of the referenceLevel property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setReferenceLevel(String value) {
		this.referenceLevel = value;
	}

	/**
	 * Gets the value of the blockNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBlockNumber() {
		return blockNumber;
	}

	/**
	 * Sets the value of the blockNumber property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setBlockNumber(String value) {
		this.blockNumber = value;
	}

}
