//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.29 at 06:09:43 PM IST 
//


package com.lca.ddt.delivery.report.inspire.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for reportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="createCoverPage" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="createDonorSignature" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="dateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="dateTimeString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="branchPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="disclaimerPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isColor" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isFaxable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isLaser" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="receivedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="receivedDateString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numCopies" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="summaryType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="omitInspireReport" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reportType", propOrder = {
    "createCoverPage",
    "createDonorSignature",
    "dateTime",
    "dateTimeString",
    "branchPhone",
    "disclaimerPhone",
    "isColor",
    "isFaxable",
    "isLaser",
    "number",
    "receivedDate",
    "receivedDateString",
    "status",
    "type",
    "numCopies",
    "summaryType",
    "omitInspireReport"
})
public class ReportType {

    protected Boolean createCoverPage;
    protected Boolean createDonorSignature;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTime;
    protected String dateTimeString;
    protected String branchPhone;
    @XmlElement(required = true)
    protected String disclaimerPhone;
    protected Boolean isColor;
    protected Boolean isFaxable;
    protected Boolean isLaser;
    @XmlElement(required = true)
    protected String number;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar receivedDate;
    protected String receivedDateString;
    @XmlElement(required = true)
    protected AdvancedStringType status;
    @XmlElement(required = true)
    protected AdvancedStringType type;
    @XmlElement(required = true)
    protected String numCopies;
    protected String summaryType;
    protected Boolean omitInspireReport;

    /**
     * Gets the value of the createCoverPage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCreateCoverPage() {
        return createCoverPage;
    }

    /**
     * Sets the value of the createCoverPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCreateCoverPage(Boolean value) {
        this.createCoverPage = value;
    }

    /**
     * Gets the value of the createDonorSignature property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCreateDonorSignature() {
        return createDonorSignature;
    }

    /**
     * Sets the value of the createDonorSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCreateDonorSignature(Boolean value) {
        this.createDonorSignature = value;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTime(XMLGregorianCalendar value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the dateTimeString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateTimeString() {
        return dateTimeString;
    }

    /**
     * Sets the value of the dateTimeString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateTimeString(String value) {
        this.dateTimeString = value;
    }

    /**
     * Gets the value of the branchPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchPhone() {
        return branchPhone;
    }

    /**
     * Sets the value of the branchPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchPhone(String value) {
        this.branchPhone = value;
    }

    /**
     * Gets the value of the disclaimerPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclaimerPhone() {
        return disclaimerPhone;
    }

    /**
     * Sets the value of the disclaimerPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclaimerPhone(String value) {
        this.disclaimerPhone = value;
    }

    /**
     * Gets the value of the isColor property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsColor() {
        return isColor;
    }

    /**
     * Sets the value of the isColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsColor(Boolean value) {
        this.isColor = value;
    }

    /**
     * Gets the value of the isFaxable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsFaxable() {
        return isFaxable;
    }

    /**
     * Sets the value of the isFaxable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsFaxable(Boolean value) {
        this.isFaxable = value;
    }

    /**
     * Gets the value of the isLaser property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsLaser() {
        return isLaser;
    }

    /**
     * Sets the value of the isLaser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsLaser(Boolean value) {
        this.isLaser = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the receivedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReceivedDate() {
        return receivedDate;
    }

    /**
     * Sets the value of the receivedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReceivedDate(XMLGregorianCalendar value) {
        this.receivedDate = value;
    }

    /**
     * Gets the value of the receivedDateString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceivedDateString() {
        return receivedDateString;
    }

    /**
     * Sets the value of the receivedDateString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceivedDateString(String value) {
        this.receivedDateString = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public AdvancedStringType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(AdvancedStringType value) {
        this.status = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public AdvancedStringType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(AdvancedStringType value) {
        this.type = value;
    }

    /**
     * Gets the value of the numCopies property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumCopies() {
        return numCopies;
    }

    /**
     * Sets the value of the numCopies property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumCopies(String value) {
        this.numCopies = value;
    }

    /**
     * Gets the value of the summaryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummaryType() {
        return summaryType;
    }

    /**
     * Sets the value of the summaryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummaryType(String value) {
        this.summaryType = value;
    }

    /**
     * Gets the value of the omitInspireReport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOmitInspireReport() {
        return omitInspireReport;
    }

    /**
     * Sets the value of the omitInspireReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOmitInspireReport(Boolean value) {
        this.omitInspireReport = value;
    }

}
