//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.29 at 06:09:43 PM IST 
//

package com.lca.ddt.delivery.report.inspire.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for specialtyType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="specialtyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="templateId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serviceMark" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specialtyReportNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clientLabID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="revision" type="{}commentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="signedBy" type="{}signedByType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Disclaimers" type="{}commentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AttachedImages" type="{}imageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Comments" type="{}commentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OrderItems" type="{}orderItemType" maxOccurs="unbounded"/>
 *         &lt;element name="Orders" type="{}orderType" maxOccurs="unbounded"/>
 *         &lt;element name="Labs" type="{}labType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FootNotes" type="{}commentType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "specialtyType", propOrder = { "templateId", "brand", "serviceMark", "title", "specialtyReportNumber",
		"clientLabID", "revision", "signedBy", "disclaimers", "attachedImages", "comments", "orderItems", "orders",
		"labs", "footNotes" })
public class SpecialtyType {

	@XmlElement(required = true)
	protected String templateId;
	@XmlElement(required = true)
	protected String brand;
	protected String serviceMark;
	protected String title;
	protected String specialtyReportNumber;
	protected String clientLabID;
	protected List<CommentType> revision;
	protected List<SignedByType> signedBy;
	@XmlElement(name = "Disclaimers")
	protected List<CommentType> disclaimers;
	@XmlElement(name = "AttachedImages")
	protected List<ImageType> attachedImages;
	@XmlElement(name = "Comments")
	protected List<CommentType> comments;
	@XmlElement(name = "OrderItems", required = true)
	protected List<OrderItemType> orderItems;
	@XmlElement(name = "Orders", required = true)
	protected List<OrderType> orders;
	@XmlElement(name = "Labs")
	protected List<LabType> labs;
	@XmlElement(name = "FootNotes")
	protected List<CommentType> footNotes;

	/**
	 * Gets the value of the templateId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTemplateId() {
		return templateId;
	}

	/**
	 * Sets the value of the templateId property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTemplateId(String value) {
		this.templateId = value;
	}

	/**
	 * Gets the value of the brand property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBrand() {
		return brand;
	}

	/**
	 * Sets the value of the brand property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setBrand(String value) {
		this.brand = value;
	}

	/**
	 * Gets the value of the serviceMark property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getServiceMark() {
		return serviceMark;
	}

	/**
	 * Sets the value of the serviceMark property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setServiceMark(String value) {
		this.serviceMark = value;
	}

	/**
	 * Gets the value of the title property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTitle(String value) {
		this.title = value;
	}

	/**
	 * Gets the value of the specialtyReportNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSpecialtyReportNumber() {
		return specialtyReportNumber;
	}

	/**
	 * Sets the value of the specialtyReportNumber property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setSpecialtyReportNumber(String value) {
		this.specialtyReportNumber = value;
	}

	/**
	 * Gets the value of the clientLabID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClientLabID() {
		return clientLabID;
	}

	/**
	 * Sets the value of the clientLabID property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setClientLabID(String value) {
		this.clientLabID = value;
	}

	/**
	 * Gets the value of the revision property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the revision property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRevision().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link CommentType }
	 * 
	 * 
	 */
	public List<CommentType> getRevision() {
		if (revision == null) {
			revision = new ArrayList<>();
		}
		return this.revision;
	}

	/**
	 * Gets the value of the signedBy property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the signedBy property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSignedBy().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link SignedByType
	 * }
	 * 
	 * 
	 */
	public List<SignedByType> getSignedBy() {
		if (signedBy == null) {
			signedBy = new ArrayList<>();
		}
		return this.signedBy;
	}

	/**
	 * Gets the value of the disclaimers property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the disclaimers property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDisclaimers().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link CommentType }
	 * 
	 * 
	 */
	public List<CommentType> getDisclaimers() {
		if (disclaimers == null) {
			disclaimers = new ArrayList<>();
		}
		return this.disclaimers;
	}

	/**
	 * Gets the value of the attachedImages property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the attachedImages property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAttachedImages().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link ImageType }
	 * 
	 * 
	 */
	public List<ImageType> getAttachedImages() {
		if (attachedImages == null) {
			attachedImages = new ArrayList<>();
		}
		return this.attachedImages;
	}

	/**
	 * Gets the value of the comments property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the comments property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getComments().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link CommentType }
	 * 
	 * 
	 */
	public List<CommentType> getComments() {
		if (comments == null) {
			comments = new ArrayList<>();
		}
		return this.comments;
	}

	/**
	 * Gets the value of the orderItems property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the orderItems property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getOrderItems().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link OrderItemType
	 * }
	 * 
	 * 
	 */
	public List<OrderItemType> getOrderItems() {
		if (orderItems == null) {
			orderItems = new ArrayList<>();
		}
		return this.orderItems;
	}

	/**
	 * Gets the value of the orders property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the orders property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getOrders().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link OrderType }
	 * 
	 * 
	 */
	public List<OrderType> getOrders() {
		if (orders == null) {
			orders = new ArrayList<>();
		}
		return this.orders;
	}

	/**
	 * Gets the value of the labs property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the labs property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getLabs().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link LabType }
	 * 
	 * 
	 */
	public List<LabType> getLabs() {
		if (labs == null) {
			labs = new ArrayList<>();
		}
		return this.labs;
	}

	/**
	 * Gets the value of the footNotes property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the footNotes property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFootNotes().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link CommentType }
	 * 
	 * 
	 */
	public List<CommentType> getFootNotes() {
		if (footNotes == null) {
			footNotes = new ArrayList<>();
		}
		return this.footNotes;
	}

}
