//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.30 at 03:09:20 PM IST 
//


package com.lca.ddt.delivery.report.input;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Accession complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Accession">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accessionNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reqNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="labInfoSystemCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accessionedBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accessionTmstp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="serviceTmstp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="icdCodes" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="accessionStatus" type="{http://www.labcorp.com/iris/messages}AccessionStatus" minOccurs="0"/>
 *         &lt;element name="accessionedLoc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="workItemLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="npi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountAddress1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountAddress2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountStateCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountZip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountFax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderingPhyDegree" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderingPhyFName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderingPhyMName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderingPhyLName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderingPhyPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderingPhyFax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mpid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="referPhyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="referPhyNPI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="salesRepName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="regionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="territoryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dob" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MRN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lpid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ccvEligible" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ccvStatus" type="{http://www.labcorp.com/iris/messages}CCVStatus" minOccurs="0"/>
 *         &lt;element name="ccvAssignedTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="patientSSN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accessionTexts" type="{http://www.labcorp.com/iris/messages}AccessionText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="accessionSpecimens" type="{http://www.labcorp.com/iris/messages}AccessionSpecimen" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="requisitionDocPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="slideCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="blockCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="tubeCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="patientMatchInd" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="clinicalHistory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PSA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PSADate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="clinicalStage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UPIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="retrievedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Accession", propOrder = {
    "accessionNum",
    "reqNumber",
    "labInfoSystemCd",
    "accessionedBy",
    "accessionTmstp",
    "serviceTmstp",
    "icdCodes",
    "accessionStatus",
    "accessionedLoc",
    "workItemLocation",
    "npi",
    "accountName",
    "accountNum",
    "accountPhone",
    "accountAddress1",
    "accountAddress2",
    "accountCity",
    "accountStateCd",
    "accountZip",
    "accountFax",
    "orderingPhyDegree",
    "orderingPhyFName",
    "orderingPhyMName",
    "orderingPhyLName",
    "orderingPhyPhone",
    "orderingPhyFax",
    "mpid",
    "referPhyName",
    "referPhyNPI",
    "salesRepName",
    "regionName",
    "territoryName",
    "dob",
    "gender",
    "mrn",
    "firstName",
    "middleName",
    "lastName",
    "lpid",
    "ccvEligible",
    "ccvStatus",
    "ccvAssignedTo",
    "patientSSN",
    "accessionTexts",
    "accessionSpecimens",
    "requisitionDocPath",
    "slideCount",
    "blockCount",
    "tubeCount",
    "patientMatchInd",
    "clinicalHistory",
    "psa",
    "psaDate",
    "clinicalStage",
    "upin",
    "retrievedDate"
})
public class Accession {

    @XmlElement(required = true)
    protected String accessionNum;
    protected String reqNumber;
    protected String labInfoSystemCd;
    @XmlElement(required = true)
    protected String accessionedBy;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar accessionTmstp;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar serviceTmstp;
    protected List<String> icdCodes;
    @XmlSchemaType(name = "string")
    protected AccessionStatus accessionStatus;
    protected String accessionedLoc;
    protected String workItemLocation;
    protected String npi;
    protected String accountName;
    protected String accountNum;
    protected String accountPhone;
    protected String accountAddress1;
    protected String accountAddress2;
    protected String accountCity;
    protected String accountStateCd;
    protected String accountZip;
    protected String accountFax;
    protected String orderingPhyDegree;
    protected String orderingPhyFName;
    protected String orderingPhyMName;
    protected String orderingPhyLName;
    protected String orderingPhyPhone;
    protected String orderingPhyFax;
    protected String mpid;
    protected String referPhyName;
    protected String referPhyNPI;
    protected String salesRepName;
    protected String regionName;
    protected String territoryName;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dob;
    protected String gender;
    @XmlElement(name = "MRN")
    protected String mrn;
    protected String firstName;
    protected String middleName;
    protected String lastName;
    protected String lpid;
    protected Boolean ccvEligible;
    @XmlSchemaType(name = "string")
    protected CCVStatus ccvStatus;
    protected String ccvAssignedTo;
    protected String patientSSN;
    protected List<AccessionText> accessionTexts;
    protected List<AccessionSpecimen> accessionSpecimens;
    protected String requisitionDocPath;
    protected Integer slideCount;
    protected Integer blockCount;
    protected Integer tubeCount;
    protected Boolean patientMatchInd;
    protected String clinicalHistory;
    @XmlElement(name = "PSA")
    protected String psa;
    @XmlElement(name = "PSADate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar psaDate;
    protected String clinicalStage;
    @XmlElement(name = "UPIN")
    protected String upin;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar retrievedDate;

    /**
     * Gets the value of the accessionNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessionNum() {
        return accessionNum;
    }

    /**
     * Sets the value of the accessionNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessionNum(String value) {
        this.accessionNum = value;
    }

    /**
     * Gets the value of the reqNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqNumber() {
        return reqNumber;
    }

    /**
     * Sets the value of the reqNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqNumber(String value) {
        this.reqNumber = value;
    }

    /**
     * Gets the value of the labInfoSystemCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabInfoSystemCd() {
        return labInfoSystemCd;
    }

    /**
     * Sets the value of the labInfoSystemCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabInfoSystemCd(String value) {
        this.labInfoSystemCd = value;
    }

    /**
     * Gets the value of the accessionedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessionedBy() {
        return accessionedBy;
    }

    /**
     * Sets the value of the accessionedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessionedBy(String value) {
        this.accessionedBy = value;
    }

    /**
     * Gets the value of the accessionTmstp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAccessionTmstp() {
        return accessionTmstp;
    }

    /**
     * Sets the value of the accessionTmstp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAccessionTmstp(XMLGregorianCalendar value) {
        this.accessionTmstp = value;
    }

    /**
     * Gets the value of the serviceTmstp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getServiceTmstp() {
        return serviceTmstp;
    }

    /**
     * Sets the value of the serviceTmstp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setServiceTmstp(XMLGregorianCalendar value) {
        this.serviceTmstp = value;
    }

    /**
     * Gets the value of the icdCodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icdCodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIcdCodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIcdCodes() {
        if (icdCodes == null) {
            icdCodes = new ArrayList<String>();
        }
        return this.icdCodes;
    }

    /**
     * Gets the value of the accessionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link AccessionStatus }
     *     
     */
    public AccessionStatus getAccessionStatus() {
        return accessionStatus;
    }

    /**
     * Sets the value of the accessionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessionStatus }
     *     
     */
    public void setAccessionStatus(AccessionStatus value) {
        this.accessionStatus = value;
    }

    /**
     * Gets the value of the accessionedLoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessionedLoc() {
        return accessionedLoc;
    }

    /**
     * Sets the value of the accessionedLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessionedLoc(String value) {
        this.accessionedLoc = value;
    }

    /**
     * Gets the value of the workItemLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkItemLocation() {
        return workItemLocation;
    }

    /**
     * Sets the value of the workItemLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkItemLocation(String value) {
        this.workItemLocation = value;
    }

    /**
     * Gets the value of the npi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpi() {
        return npi;
    }

    /**
     * Sets the value of the npi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpi(String value) {
        this.npi = value;
    }

    /**
     * Gets the value of the accountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * Sets the value of the accountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountName(String value) {
        this.accountName = value;
    }

    /**
     * Gets the value of the accountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNum() {
        return accountNum;
    }

    /**
     * Sets the value of the accountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNum(String value) {
        this.accountNum = value;
    }

    /**
     * Gets the value of the accountPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountPhone() {
        return accountPhone;
    }

    /**
     * Sets the value of the accountPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountPhone(String value) {
        this.accountPhone = value;
    }

    /**
     * Gets the value of the accountAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountAddress1() {
        return accountAddress1;
    }

    /**
     * Sets the value of the accountAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountAddress1(String value) {
        this.accountAddress1 = value;
    }

    /**
     * Gets the value of the accountAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountAddress2() {
        return accountAddress2;
    }

    /**
     * Sets the value of the accountAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountAddress2(String value) {
        this.accountAddress2 = value;
    }

    /**
     * Gets the value of the accountCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountCity() {
        return accountCity;
    }

    /**
     * Sets the value of the accountCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountCity(String value) {
        this.accountCity = value;
    }

    /**
     * Gets the value of the accountStateCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountStateCd() {
        return accountStateCd;
    }

    /**
     * Sets the value of the accountStateCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountStateCd(String value) {
        this.accountStateCd = value;
    }

    /**
     * Gets the value of the accountZip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountZip() {
        return accountZip;
    }

    /**
     * Sets the value of the accountZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountZip(String value) {
        this.accountZip = value;
    }

    /**
     * Gets the value of the accountFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountFax() {
        return accountFax;
    }

    /**
     * Sets the value of the accountFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountFax(String value) {
        this.accountFax = value;
    }

    /**
     * Gets the value of the orderingPhyDegree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderingPhyDegree() {
        return orderingPhyDegree;
    }

    /**
     * Sets the value of the orderingPhyDegree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderingPhyDegree(String value) {
        this.orderingPhyDegree = value;
    }

    /**
     * Gets the value of the orderingPhyFName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderingPhyFName() {
        return orderingPhyFName;
    }

    /**
     * Sets the value of the orderingPhyFName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderingPhyFName(String value) {
        this.orderingPhyFName = value;
    }

    /**
     * Gets the value of the orderingPhyMName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderingPhyMName() {
        return orderingPhyMName;
    }

    /**
     * Sets the value of the orderingPhyMName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderingPhyMName(String value) {
        this.orderingPhyMName = value;
    }

    /**
     * Gets the value of the orderingPhyLName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderingPhyLName() {
        return orderingPhyLName;
    }

    /**
     * Sets the value of the orderingPhyLName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderingPhyLName(String value) {
        this.orderingPhyLName = value;
    }

    /**
     * Gets the value of the orderingPhyPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderingPhyPhone() {
        return orderingPhyPhone;
    }

    /**
     * Sets the value of the orderingPhyPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderingPhyPhone(String value) {
        this.orderingPhyPhone = value;
    }

    /**
     * Gets the value of the orderingPhyFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderingPhyFax() {
        return orderingPhyFax;
    }

    /**
     * Sets the value of the orderingPhyFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderingPhyFax(String value) {
        this.orderingPhyFax = value;
    }

    /**
     * Gets the value of the mpid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMpid() {
        return mpid;
    }

    /**
     * Sets the value of the mpid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMpid(String value) {
        this.mpid = value;
    }

    /**
     * Gets the value of the referPhyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferPhyName() {
        return referPhyName;
    }

    /**
     * Sets the value of the referPhyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferPhyName(String value) {
        this.referPhyName = value;
    }

    /**
     * Gets the value of the referPhyNPI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferPhyNPI() {
        return referPhyNPI;
    }

    /**
     * Sets the value of the referPhyNPI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferPhyNPI(String value) {
        this.referPhyNPI = value;
    }

    /**
     * Gets the value of the salesRepName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesRepName() {
        return salesRepName;
    }

    /**
     * Sets the value of the salesRepName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesRepName(String value) {
        this.salesRepName = value;
    }

    /**
     * Gets the value of the regionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * Sets the value of the regionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionName(String value) {
        this.regionName = value;
    }

    /**
     * Gets the value of the territoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerritoryName() {
        return territoryName;
    }

    /**
     * Sets the value of the territoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerritoryName(String value) {
        this.territoryName = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDob() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDob(XMLGregorianCalendar value) {
        this.dob = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the mrn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMRN() {
        return mrn;
    }

    /**
     * Sets the value of the mrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMRN(String value) {
        this.mrn = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the lpid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLpid() {
        return lpid;
    }

    /**
     * Sets the value of the lpid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLpid(String value) {
        this.lpid = value;
    }

    /**
     * Gets the value of the ccvEligible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCcvEligible() {
        return ccvEligible;
    }

    /**
     * Sets the value of the ccvEligible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCcvEligible(Boolean value) {
        this.ccvEligible = value;
    }

    /**
     * Gets the value of the ccvStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CCVStatus }
     *     
     */
    public CCVStatus getCcvStatus() {
        return ccvStatus;
    }

    /**
     * Sets the value of the ccvStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CCVStatus }
     *     
     */
    public void setCcvStatus(CCVStatus value) {
        this.ccvStatus = value;
    }

    /**
     * Gets the value of the ccvAssignedTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcvAssignedTo() {
        return ccvAssignedTo;
    }

    /**
     * Sets the value of the ccvAssignedTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcvAssignedTo(String value) {
        this.ccvAssignedTo = value;
    }

    /**
     * Gets the value of the patientSSN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientSSN() {
        return patientSSN;
    }

    /**
     * Sets the value of the patientSSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientSSN(String value) {
        this.patientSSN = value;
    }

    /**
     * Gets the value of the accessionTexts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessionTexts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessionTexts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccessionText }
     * 
     * 
     */
    public List<AccessionText> getAccessionTexts() {
        if (accessionTexts == null) {
            accessionTexts = new ArrayList<AccessionText>();
        }
        return this.accessionTexts;
    }

    /**
     * Gets the value of the accessionSpecimens property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessionSpecimens property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessionSpecimens().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccessionSpecimen }
     * 
     * 
     */
    public List<AccessionSpecimen> getAccessionSpecimens() {
        if (accessionSpecimens == null) {
            accessionSpecimens = new ArrayList<AccessionSpecimen>();
        }
        return this.accessionSpecimens;
    }

    /**
     * Gets the value of the requisitionDocPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequisitionDocPath() {
        return requisitionDocPath;
    }

    /**
     * Sets the value of the requisitionDocPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequisitionDocPath(String value) {
        this.requisitionDocPath = value;
    }

    /**
     * Gets the value of the slideCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSlideCount() {
        return slideCount;
    }

    /**
     * Sets the value of the slideCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSlideCount(Integer value) {
        this.slideCount = value;
    }

    /**
     * Gets the value of the blockCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBlockCount() {
        return blockCount;
    }

    /**
     * Sets the value of the blockCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBlockCount(Integer value) {
        this.blockCount = value;
    }

    /**
     * Gets the value of the tubeCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTubeCount() {
        return tubeCount;
    }

    /**
     * Sets the value of the tubeCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTubeCount(Integer value) {
        this.tubeCount = value;
    }

    /**
     * Gets the value of the patientMatchInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPatientMatchInd() {
        return patientMatchInd;
    }

    /**
     * Sets the value of the patientMatchInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPatientMatchInd(Boolean value) {
        this.patientMatchInd = value;
    }

    /**
     * Gets the value of the clinicalHistory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClinicalHistory() {
        return clinicalHistory;
    }

    /**
     * Sets the value of the clinicalHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClinicalHistory(String value) {
        this.clinicalHistory = value;
    }

    /**
     * Gets the value of the psa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPSA() {
        return psa;
    }

    /**
     * Sets the value of the psa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPSA(String value) {
        this.psa = value;
    }

    /**
     * Gets the value of the psaDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPSADate() {
        return psaDate;
    }

    /**
     * Sets the value of the psaDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPSADate(XMLGregorianCalendar value) {
        this.psaDate = value;
    }

    /**
     * Gets the value of the clinicalStage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClinicalStage() {
        return clinicalStage;
    }

    /**
     * Sets the value of the clinicalStage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClinicalStage(String value) {
        this.clinicalStage = value;
    }

    /**
     * Gets the value of the upin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUPIN() {
        return upin;
    }

    /**
     * Sets the value of the upin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUPIN(String value) {
        this.upin = value;
    }

    /**
     * Gets the value of the retrievedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRetrievedDate() {
        return retrievedDate;
    }

    /**
     * Sets the value of the retrievedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRetrievedDate(XMLGregorianCalendar value) {
        this.retrievedDate = value;
    }

}
