//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.30 at 03:09:20 PM IST 
//


package com.lca.ddt.delivery.report.input;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AccessionSpecimen complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccessionSpecimen">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="specimenId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="clientSpecimenID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specimenType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specimenDescr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specimenSiteCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specimenSiteDescr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specimenTransportDescr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="typeOfFixative" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fixativeDurationHH" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="fixativeDurationMM" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="specimenReceivedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="specimenCollectedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="panels" type="{http://www.labcorp.com/iris/messages}Panel" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="specimenTests" type="{http://www.labcorp.com/iris/messages}SpecimenTest" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="specimenResulting" type="{http://www.labcorp.com/iris/messages}SpecimenResulting" minOccurs="0"/>
 *         &lt;element name="timeToFixationHH" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="timeToFixationMM" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="specimenText" type="{http://www.labcorp.com/iris/messages}SpecimenText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="labCorpSpecimenId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="blocks" type="{http://www.labcorp.com/iris/messages}Block" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="timeToFixGeneralText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="durationOfFixGeneralText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="timeToFixNotProvided" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="durationOfFixNotProvided" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="timeToFixationKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="durationOfFixativeKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="grossDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccessionSpecimen", propOrder = {
    "specimenId",
    "clientSpecimenID",
    "specimenType",
    "specimenDescr",
    "specimenSiteCd",
    "specimenSiteDescr",
    "specimenTransportDescr",
    "typeOfFixative",
    "fixativeDurationHH",
    "fixativeDurationMM",
    "specimenReceivedDateTime",
    "specimenCollectedDateTime",
    "panels",
    "specimenTests",
    "specimenResulting",
    "timeToFixationHH",
    "timeToFixationMM",
    "specimenText",
    "labCorpSpecimenId",
    "blocks",
    "timeToFixGeneralText",
    "durationOfFixGeneralText",
    "timeToFixNotProvided",
    "durationOfFixNotProvided",
    "timeToFixationKey",
    "durationOfFixativeKey",
    "grossDescription"
})
public class AccessionSpecimen {

    @XmlElement(required = true)
    protected String specimenId;
    protected String clientSpecimenID;
    protected String specimenType;
    protected String specimenDescr;
    protected String specimenSiteCd;
    protected String specimenSiteDescr;
    protected String specimenTransportDescr;
    protected String typeOfFixative;
    protected Integer fixativeDurationHH;
    protected Integer fixativeDurationMM;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar specimenReceivedDateTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar specimenCollectedDateTime;
    @XmlElement(nillable = true)
    protected List<Panel> panels;
    @XmlElement(nillable = true)
    protected List<SpecimenTest> specimenTests;
    @XmlElementRef(name = "specimenResulting", type = JAXBElement.class, required = false)
    protected JAXBElement<SpecimenResulting> specimenResulting;
    protected Integer timeToFixationHH;
    protected Integer timeToFixationMM;
    protected List<SpecimenText> specimenText;
    protected String labCorpSpecimenId;
    protected List<Block> blocks;
    protected String timeToFixGeneralText;
    protected String durationOfFixGeneralText;
    protected String timeToFixNotProvided;
    protected String durationOfFixNotProvided;
    protected String timeToFixationKey;
    protected String durationOfFixativeKey;
    protected String grossDescription;

    /**
     * Gets the value of the specimenId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecimenId() {
        return specimenId;
    }

    /**
     * Sets the value of the specimenId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecimenId(String value) {
        this.specimenId = value;
    }

    /**
     * Gets the value of the clientSpecimenID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientSpecimenID() {
        return clientSpecimenID;
    }

    /**
     * Sets the value of the clientSpecimenID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientSpecimenID(String value) {
        this.clientSpecimenID = value;
    }

    /**
     * Gets the value of the specimenType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecimenType() {
        return specimenType;
    }

    /**
     * Sets the value of the specimenType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecimenType(String value) {
        this.specimenType = value;
    }

    /**
     * Gets the value of the specimenDescr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecimenDescr() {
        return specimenDescr;
    }

    /**
     * Sets the value of the specimenDescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecimenDescr(String value) {
        this.specimenDescr = value;
    }

    /**
     * Gets the value of the specimenSiteCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecimenSiteCd() {
        return specimenSiteCd;
    }

    /**
     * Sets the value of the specimenSiteCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecimenSiteCd(String value) {
        this.specimenSiteCd = value;
    }

    /**
     * Gets the value of the specimenSiteDescr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecimenSiteDescr() {
        return specimenSiteDescr;
    }

    /**
     * Sets the value of the specimenSiteDescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecimenSiteDescr(String value) {
        this.specimenSiteDescr = value;
    }

    /**
     * Gets the value of the specimenTransportDescr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecimenTransportDescr() {
        return specimenTransportDescr;
    }

    /**
     * Sets the value of the specimenTransportDescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecimenTransportDescr(String value) {
        this.specimenTransportDescr = value;
    }

    /**
     * Gets the value of the typeOfFixative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfFixative() {
        return typeOfFixative;
    }

    /**
     * Sets the value of the typeOfFixative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfFixative(String value) {
        this.typeOfFixative = value;
    }

    /**
     * Gets the value of the fixativeDurationHH property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFixativeDurationHH() {
        return fixativeDurationHH;
    }

    /**
     * Sets the value of the fixativeDurationHH property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFixativeDurationHH(Integer value) {
        this.fixativeDurationHH = value;
    }

    /**
     * Gets the value of the fixativeDurationMM property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFixativeDurationMM() {
        return fixativeDurationMM;
    }

    /**
     * Sets the value of the fixativeDurationMM property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFixativeDurationMM(Integer value) {
        this.fixativeDurationMM = value;
    }

    /**
     * Gets the value of the specimenReceivedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSpecimenReceivedDateTime() {
        return specimenReceivedDateTime;
    }

    /**
     * Sets the value of the specimenReceivedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSpecimenReceivedDateTime(XMLGregorianCalendar value) {
        this.specimenReceivedDateTime = value;
    }

    /**
     * Gets the value of the specimenCollectedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSpecimenCollectedDateTime() {
        return specimenCollectedDateTime;
    }

    /**
     * Sets the value of the specimenCollectedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSpecimenCollectedDateTime(XMLGregorianCalendar value) {
        this.specimenCollectedDateTime = value;
    }

    /**
     * Gets the value of the panels property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the panels property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPanels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Panel }
     * 
     * 
     */
    public List<Panel> getPanels() {
        if (panels == null) {
            panels = new ArrayList<Panel>();
        }
        return this.panels;
    }

    /**
     * Gets the value of the specimenTests property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specimenTests property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecimenTests().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpecimenTest }
     * 
     * 
     */
    public List<SpecimenTest> getSpecimenTests() {
        if (specimenTests == null) {
            specimenTests = new ArrayList<SpecimenTest>();
        }
        return this.specimenTests;
    }

    /**
     * Gets the value of the specimenResulting property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SpecimenResulting }{@code >}
     *     
     */
    public JAXBElement<SpecimenResulting> getSpecimenResulting() {
        return specimenResulting;
    }

    /**
     * Sets the value of the specimenResulting property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SpecimenResulting }{@code >}
     *     
     */
    public void setSpecimenResulting(JAXBElement<SpecimenResulting> value) {
        this.specimenResulting = value;
    }

    /**
     * Gets the value of the timeToFixationHH property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTimeToFixationHH() {
        return timeToFixationHH;
    }

    /**
     * Sets the value of the timeToFixationHH property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTimeToFixationHH(Integer value) {
        this.timeToFixationHH = value;
    }

    /**
     * Gets the value of the timeToFixationMM property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTimeToFixationMM() {
        return timeToFixationMM;
    }

    /**
     * Sets the value of the timeToFixationMM property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTimeToFixationMM(Integer value) {
        this.timeToFixationMM = value;
    }

    /**
     * Gets the value of the specimenText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specimenText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecimenText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpecimenText }
     * 
     * 
     */
    public List<SpecimenText> getSpecimenText() {
        if (specimenText == null) {
            specimenText = new ArrayList<SpecimenText>();
        }
        return this.specimenText;
    }

    /**
     * Gets the value of the labCorpSpecimenId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabCorpSpecimenId() {
        return labCorpSpecimenId;
    }

    /**
     * Sets the value of the labCorpSpecimenId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabCorpSpecimenId(String value) {
        this.labCorpSpecimenId = value;
    }

    /**
     * Gets the value of the blocks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the blocks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBlocks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Block }
     * 
     * 
     */
    public List<Block> getBlocks() {
        if (blocks == null) {
            blocks = new ArrayList<Block>();
        }
        return this.blocks;
    }

    /**
     * Gets the value of the timeToFixGeneralText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeToFixGeneralText() {
        return timeToFixGeneralText;
    }

    /**
     * Sets the value of the timeToFixGeneralText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeToFixGeneralText(String value) {
        this.timeToFixGeneralText = value;
    }

    /**
     * Gets the value of the durationOfFixGeneralText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationOfFixGeneralText() {
        return durationOfFixGeneralText;
    }

    /**
     * Sets the value of the durationOfFixGeneralText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationOfFixGeneralText(String value) {
        this.durationOfFixGeneralText = value;
    }

    /**
     * Gets the value of the timeToFixNotProvided property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeToFixNotProvided() {
        return timeToFixNotProvided;
    }

    /**
     * Sets the value of the timeToFixNotProvided property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeToFixNotProvided(String value) {
        this.timeToFixNotProvided = value;
    }

    /**
     * Gets the value of the durationOfFixNotProvided property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationOfFixNotProvided() {
        return durationOfFixNotProvided;
    }

    /**
     * Sets the value of the durationOfFixNotProvided property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationOfFixNotProvided(String value) {
        this.durationOfFixNotProvided = value;
    }

    /**
     * Gets the value of the timeToFixationKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeToFixationKey() {
        return timeToFixationKey;
    }

    /**
     * Sets the value of the timeToFixationKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeToFixationKey(String value) {
        this.timeToFixationKey = value;
    }

    /**
     * Gets the value of the durationOfFixativeKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationOfFixativeKey() {
        return durationOfFixativeKey;
    }

    /**
     * Sets the value of the durationOfFixativeKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationOfFixativeKey(String value) {
        this.durationOfFixativeKey = value;
    }

    /**
     * Gets the value of the grossDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrossDescription() {
        return grossDescription;
    }

    /**
     * Sets the value of the grossDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrossDescription(String value) {
        this.grossDescription = value;
    }

}
