//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.30 at 03:09:20 PM IST 
//


package com.lca.ddt.delivery.report.input;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CaseAssignments complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CaseAssignments">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CaseAssignmentDTO" type="{http://www.labcorp.com/iris/messages}CaseAssignmentDTO"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CaseAssignments", propOrder = {
    "caseAssignmentDTO"
})
public class CaseAssignments {

    @XmlElement(name = "CaseAssignmentDTO", required = true)
    protected CaseAssignmentDTO caseAssignmentDTO;

    /**
     * Gets the value of the caseAssignmentDTO property.
     * 
     * @return
     *     possible object is
     *     {@link CaseAssignmentDTO }
     *     
     */
    public CaseAssignmentDTO getCaseAssignmentDTO() {
        return caseAssignmentDTO;
    }

    /**
     * Sets the value of the caseAssignmentDTO property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseAssignmentDTO }
     *     
     */
    public void setCaseAssignmentDTO(CaseAssignmentDTO value) {
        this.caseAssignmentDTO = value;
    }

}
