//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.30 at 03:09:20 PM IST 
//


package com.lca.ddt.delivery.report.input;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CCVTextType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CCVTextType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DIAGSMRY"/>
 *     &lt;enumeration value="TESTNAME"/>
 *     &lt;enumeration value="WBC"/>
 *     &lt;enumeration value="HGB"/>
 *     &lt;enumeration value="PLT"/>
 *     &lt;enumeration value="SUBMITTEDCBC"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CCVTextType")
@XmlEnum
public enum CCVTextType {

    DIAGSMRY,
    TESTNAME,
    WBC,
    HGB,
    PLT,
    SUBMITTEDCBC;

    public String value() {
        return name();
    }

    public static CCVTextType fromValue(String v) {
        return valueOf(v);
    }

}
