//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.30 at 03:09:20 PM IST 
//


package com.lca.ddt.delivery.report.input;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConcurrentCase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConcurrentCase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reportNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="categoryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="seqNum" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="reportSignedTimestamp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rptStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reportSignedLoginId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ccvConcurrentCaseText" type="{http://www.labcorp.com/iris/messages}CCVText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ccvConcurrentCaseImages" type="{http://www.labcorp.com/iris/messages}CCVConcurrentCaseImage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="specimenType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cancelReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="templateId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isReport" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="reportSpecimen" type="{http://www.labcorp.com/iris/messages}AccessionSpecimen" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="caseReportTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isSignedByPathologist" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConcurrentCase", propOrder = {
    "reportNumber",
    "categoryName",
    "seqNum",
    "reportSignedTimestamp",
    "rptStatus",
    "reportSignedLoginId",
    "ccvConcurrentCaseText",
    "ccvConcurrentCaseImages",
    "specimenType",
    "cancelReason",
    "templateId",
    "isReport",
    "reportSpecimen",
    "caseReportTitle",
    "isSignedByPathologist"
})
public class ConcurrentCase {

    protected String reportNumber;
    protected String categoryName;
    protected Integer seqNum;
    protected String reportSignedTimestamp;
    protected String rptStatus;
    protected String reportSignedLoginId;
    protected List<CCVText> ccvConcurrentCaseText;
    protected List<CCVConcurrentCaseImage> ccvConcurrentCaseImages;
    protected String specimenType;
    protected String cancelReason;
    protected String templateId;
    protected Boolean isReport;
    protected List<AccessionSpecimen> reportSpecimen;
    protected String caseReportTitle;
    protected Boolean isSignedByPathologist;

    /**
     * Gets the value of the reportNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportNumber() {
        return reportNumber;
    }

    /**
     * Sets the value of the reportNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportNumber(String value) {
        this.reportNumber = value;
    }

    /**
     * Gets the value of the categoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * Sets the value of the categoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryName(String value) {
        this.categoryName = value;
    }

    /**
     * Gets the value of the seqNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSeqNum() {
        return seqNum;
    }

    /**
     * Sets the value of the seqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSeqNum(Integer value) {
        this.seqNum = value;
    }

    /**
     * Gets the value of the reportSignedTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportSignedTimestamp() {
        return reportSignedTimestamp;
    }

    /**
     * Sets the value of the reportSignedTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportSignedTimestamp(String value) {
        this.reportSignedTimestamp = value;
    }

    /**
     * Gets the value of the rptStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptStatus() {
        return rptStatus;
    }

    /**
     * Sets the value of the rptStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptStatus(String value) {
        this.rptStatus = value;
    }

    /**
     * Gets the value of the reportSignedLoginId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportSignedLoginId() {
        return reportSignedLoginId;
    }

    /**
     * Sets the value of the reportSignedLoginId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportSignedLoginId(String value) {
        this.reportSignedLoginId = value;
    }

    /**
     * Gets the value of the ccvConcurrentCaseText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ccvConcurrentCaseText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCcvConcurrentCaseText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CCVText }
     * 
     * 
     */
    public List<CCVText> getCcvConcurrentCaseText() {
        if (ccvConcurrentCaseText == null) {
            ccvConcurrentCaseText = new ArrayList<CCVText>();
        }
        return this.ccvConcurrentCaseText;
    }

    /**
     * Gets the value of the ccvConcurrentCaseImages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ccvConcurrentCaseImages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCcvConcurrentCaseImages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CCVConcurrentCaseImage }
     * 
     * 
     */
    public List<CCVConcurrentCaseImage> getCcvConcurrentCaseImages() {
        if (ccvConcurrentCaseImages == null) {
            ccvConcurrentCaseImages = new ArrayList<CCVConcurrentCaseImage>();
        }
        return this.ccvConcurrentCaseImages;
    }

    /**
     * Gets the value of the specimenType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecimenType() {
        return specimenType;
    }

    /**
     * Sets the value of the specimenType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecimenType(String value) {
        this.specimenType = value;
    }

    /**
     * Gets the value of the cancelReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * Sets the value of the cancelReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelReason(String value) {
        this.cancelReason = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * Sets the value of the templateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateId(String value) {
        this.templateId = value;
    }

    /**
     * Gets the value of the isReport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsReport() {
        return isReport;
    }

    /**
     * Sets the value of the isReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsReport(Boolean value) {
        this.isReport = value;
    }

    /**
     * Gets the value of the reportSpecimen property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportSpecimen property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportSpecimen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccessionSpecimen }
     * 
     * 
     */
    public List<AccessionSpecimen> getReportSpecimen() {
        if (reportSpecimen == null) {
            reportSpecimen = new ArrayList<AccessionSpecimen>();
        }
        return this.reportSpecimen;
    }

    /**
     * Gets the value of the caseReportTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseReportTitle() {
        return caseReportTitle;
    }

    /**
     * Sets the value of the caseReportTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseReportTitle(String value) {
        this.caseReportTitle = value;
    }

    /**
     * Gets the value of the isSignedByPathologist property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSignedByPathologist() {
        return isSignedByPathologist;
    }

    /**
     * Sets the value of the isSignedByPathologist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSignedByPathologist(Boolean value) {
        this.isSignedByPathologist = value;
    }

}
