//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.30 at 03:09:20 PM IST 
//


package com.lca.ddt.delivery.report.input;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EVENTTYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EVENTTYPE">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ACCESSIONADD"/>
 *     &lt;enumeration value="ACCESSIONEDIT"/>
 *     &lt;enumeration value="ACCESSIONCLOSE"/>
 *     &lt;enumeration value="CASESIGN"/>
 *     &lt;enumeration value="CASEPREVIEW"/>
 *     &lt;enumeration value="MODIFYORDER"/>
 *     &lt;enumeration value="IRISTESTADD"/>
 *     &lt;enumeration value="IRISTESTCANCEL"/>
 *     &lt;enumeration value="IRISTESTREVISE"/>
 *     &lt;enumeration value="CCVQUALIFY"/>
 *     &lt;enumeration value="CCVDISQUALIFY"/>
 *     &lt;enumeration value="CCVREVISE"/>
 *     &lt;enumeration value="CONVERTGLOBAL"/>
 *     &lt;enumeration value="CCVSIGN"/>
 *     &lt;enumeration value="CCVPREVIEW"/>
 *     &lt;enumeration value="CASEASSIGNMENT"/>
 *     &lt;enumeration value="CASEUNASSIGNMENT"/>
 *     &lt;enumeration value="TECHCOMPLETE"/>
 *     &lt;enumeration value="VANTAGE_ORDER"/>
 *     &lt;enumeration value="VANTAGE_CANCEL"/>
 *     &lt;enumeration value="VANTAGE_EDIT"/>
 *     &lt;enumeration value="VANTAGE_MICR_PRINT_COMPLETE"/>
 *     &lt;enumeration value="VANTAGE_BEGIN_STAIN"/>
 *     &lt;enumeration value="VANTAGE_STAIN_COMPLETE"/>
 *     &lt;enumeration value="VANTAGE_EMBED_COMPLETE"/>
 *     &lt;enumeration value="VANTAGE_IMAGING_COMPLETE"/>
 *     &lt;enumeration value="LEGACYACCESSIONADD"/>
 *     &lt;enumeration value="LEGACYACCESSIONEDIT"/>
 *     &lt;enumeration value="SPECIMENADD"/>
 *     &lt;enumeration value="SPECIMENEDIT"/>
 *     &lt;enumeration value="LEGACYTESTADD"/>
 *     &lt;enumeration value="LEGACYTESTCANCEL"/>
 *     &lt;enumeration value="LEGACYCASEADD"/>
 *     &lt;enumeration value="LEGACYTESTREVISE"/>
 *     &lt;enumeration value="REASSIGNWORKITEMLOC"/>
 *     &lt;enumeration value="VANTAGE_ASSEMBLED_COMPLETE"/>
 *     &lt;enumeration value="VANTAGE_ADD_CASSETTE"/>
 *     &lt;enumeration value="VANTAGE_ADD_SLIDE"/>
 *     &lt;enumeration value="VANTAGE_MARKED_COMPLETE"/>
 *     &lt;enumeration value="VIRTUOSO_CASEADD"/>
 *     &lt;enumeration value="VIRTUOSO_CASEMODIFY"/>
 *     &lt;enumeration value="VIRTUOSO_SLIDEREJECTED"/>
 *     &lt;enumeration value="VANTAGE_ADD_RV_SLIDE"/>
 *     &lt;enumeration value="VANTAGE_CANCEL_RV_SLIDE"/>
 *     &lt;enumeration value="VANTAGE_ADD_POSTIVECONTROL"/>
 *     &lt;enumeration value="VANTAGE_REMOVE_POSTIVECONTROL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EVENTTYPE")
@XmlEnum
public enum EVENTTYPE {

    ACCESSIONADD,
    ACCESSIONEDIT,
    ACCESSIONCLOSE,
    CASESIGN,
    CASEPREVIEW,
    MODIFYORDER,
    IRISTESTADD,
    IRISTESTCANCEL,
    IRISTESTREVISE,
    CCVQUALIFY,
    CCVDISQUALIFY,
    CCVREVISE,
    CONVERTGLOBAL,
    CCVSIGN,
    CCVPREVIEW,
    CASEASSIGNMENT,
    CASEUNASSIGNMENT,
    TECHCOMPLETE,
    VANTAGE_ORDER,
    VANTAGE_CANCEL,
    VANTAGE_EDIT,
    VANTAGE_MICR_PRINT_COMPLETE,
    VANTAGE_BEGIN_STAIN,
    VANTAGE_STAIN_COMPLETE,
    VANTAGE_EMBED_COMPLETE,
    VANTAGE_IMAGING_COMPLETE,
    LEGACYACCESSIONADD,
    LEGACYACCESSIONEDIT,
    SPECIMENADD,
    SPECIMENEDIT,
    LEGACYTESTADD,
    LEGACYTESTCANCEL,
    LEGACYCASEADD,
    LEGACYTESTREVISE,
    REASSIGNWORKITEMLOC,
    VANTAGE_ASSEMBLED_COMPLETE,
    VANTAGE_ADD_CASSETTE,
    VANTAGE_ADD_SLIDE,
    VANTAGE_MARKED_COMPLETE,
    VIRTUOSO_CASEADD,
    VIRTUOSO_CASEMODIFY,
    VIRTUOSO_SLIDEREJECTED,
    VANTAGE_ADD_RV_SLIDE,
    VANTAGE_CANCEL_RV_SLIDE,
    VANTAGE_ADD_POSTIVECONTROL,
    VANTAGE_REMOVE_POSTIVECONTROL;

    public String value() {
        return name();
    }

    public static EVENTTYPE fromValue(String v) {
        return valueOf(v);
    }

}
