//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.30 at 03:09:20 PM IST 
//


package com.lca.ddt.delivery.report.input;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Event complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Event">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eventName" type="{http://www.labcorp.com/iris/messages}EVENTTYPE"/>
 *         &lt;element name="accessionNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reasonType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reasonCmnts" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="specimenId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="specimenTests" type="{http://www.labcorp.com/iris/messages}SpecimenTest" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="loginId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateTimeStmp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="cancelCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Event", propOrder = {
    "eventName",
    "accessionNum",
    "reasonType",
    "reasonCmnts",
    "specimenId",
    "specimenTests",
    "loginId",
    "dateTimeStmp",
    "cancelCode"
})
public class Event {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected EVENTTYPE eventName;
    @XmlElement(required = true)
    protected String accessionNum;
    @XmlElement(required = true)
    protected String reasonType;
    @XmlElement(required = true)
    protected String reasonCmnts;
    @XmlElement(required = true)
    protected String specimenId;
    @XmlElement(nillable = true)
    protected List<SpecimenTest> specimenTests;
    @XmlElement(required = true)
    protected String loginId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTimeStmp;
    @XmlElement(required = true)
    protected String cancelCode;

    /**
     * Gets the value of the eventName property.
     * 
     * @return
     *     possible object is
     *     {@link EVENTTYPE }
     *     
     */
    public EVENTTYPE getEventName() {
        return eventName;
    }

    /**
     * Sets the value of the eventName property.
     * 
     * @param value
     *     allowed object is
     *     {@link EVENTTYPE }
     *     
     */
    public void setEventName(EVENTTYPE value) {
        this.eventName = value;
    }

    /**
     * Gets the value of the accessionNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessionNum() {
        return accessionNum;
    }

    /**
     * Sets the value of the accessionNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessionNum(String value) {
        this.accessionNum = value;
    }

    /**
     * Gets the value of the reasonType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonType() {
        return reasonType;
    }

    /**
     * Sets the value of the reasonType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonType(String value) {
        this.reasonType = value;
    }

    /**
     * Gets the value of the reasonCmnts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCmnts() {
        return reasonCmnts;
    }

    /**
     * Sets the value of the reasonCmnts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCmnts(String value) {
        this.reasonCmnts = value;
    }

    /**
     * Gets the value of the specimenId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecimenId() {
        return specimenId;
    }

    /**
     * Sets the value of the specimenId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecimenId(String value) {
        this.specimenId = value;
    }

    /**
     * Gets the value of the specimenTests property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specimenTests property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecimenTests().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpecimenTest }
     * 
     * 
     */
    public List<SpecimenTest> getSpecimenTests() {
        if (specimenTests == null) {
            specimenTests = new ArrayList<SpecimenTest>();
        }
        return this.specimenTests;
    }

    /**
     * Gets the value of the loginId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * Sets the value of the loginId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoginId(String value) {
        this.loginId = value;
    }

    /**
     * Gets the value of the dateTimeStmp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTimeStmp() {
        return dateTimeStmp;
    }

    /**
     * Sets the value of the dateTimeStmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTimeStmp(XMLGregorianCalendar value) {
        this.dateTimeStmp = value;
    }

    /**
     * Gets the value of the cancelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelCode() {
        return cancelCode;
    }

    /**
     * Sets the value of the cancelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelCode(String value) {
        this.cancelCode = value;
    }

}
