//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.30 at 03:09:20 PM IST 
//


package com.lca.ddt.delivery.report.input;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="event" type="{http://www.labcorp.com/iris/messages}EVENTTYPE"/>
 *         &lt;element name="msgOrigin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accessions" type="{http://www.labcorp.com/iris/messages}Accession" minOccurs="0"/>
 *         &lt;element name="ccvConcurrentCases" type="{http://www.labcorp.com/iris/messages}ConcurrentCase" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ccvHistoricalAccession" type="{http://www.labcorp.com/iris/messages}CCVHistoricalAccession" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "event",
    "msgOrigin",
    "accessions",
    "ccvConcurrentCases",
    "ccvHistoricalAccession"
})
@XmlRootElement(name = "IRISCCVMESSAGE")
public class IRISCCVMESSAGE {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected EVENTTYPE event;
    protected String msgOrigin;
    protected Accession accessions;
    protected List<ConcurrentCase> ccvConcurrentCases;
    protected List<CCVHistoricalAccession> ccvHistoricalAccession;

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link EVENTTYPE }
     *     
     */
    public EVENTTYPE getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link EVENTTYPE }
     *     
     */
    public void setEvent(EVENTTYPE value) {
        this.event = value;
    }

    /**
     * Gets the value of the msgOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgOrigin() {
        return msgOrigin;
    }

    /**
     * Sets the value of the msgOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgOrigin(String value) {
        this.msgOrigin = value;
    }

    /**
     * Gets the value of the accessions property.
     * 
     * @return
     *     possible object is
     *     {@link Accession }
     *     
     */
    public Accession getAccessions() {
        return accessions;
    }

    /**
     * Sets the value of the accessions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accession }
     *     
     */
    public void setAccessions(Accession value) {
        this.accessions = value;
    }

    /**
     * Gets the value of the ccvConcurrentCases property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ccvConcurrentCases property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCcvConcurrentCases().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConcurrentCase }
     * 
     * 
     */
    public List<ConcurrentCase> getCcvConcurrentCases() {
        if (ccvConcurrentCases == null) {
            ccvConcurrentCases = new ArrayList<ConcurrentCase>();
        }
        return this.ccvConcurrentCases;
    }

    /**
     * Gets the value of the ccvHistoricalAccession property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ccvHistoricalAccession property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCcvHistoricalAccession().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CCVHistoricalAccession }
     * 
     * 
     */
    public List<CCVHistoricalAccession> getCcvHistoricalAccession() {
        if (ccvHistoricalAccession == null) {
            ccvHistoricalAccession = new ArrayList<CCVHistoricalAccession>();
        }
        return this.ccvHistoricalAccession;
    }

}
