//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.30 at 03:09:20 PM IST 
//


package com.lca.ddt.delivery.report.input;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lca.ddt.delivery.report.input package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AccessionSpecimenSpecimenResulting_QNAME = new QName("", "specimenResulting");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lca.ddt.delivery.report.input
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IRISPathwaysTechCompleteMessage }
     * 
     */
    public IRISPathwaysTechCompleteMessage createIRISPathwaysTechCompleteMessage() {
        return new IRISPathwaysTechCompleteMessage();
    }

    /**
     * Create an instance of {@link Accession }
     * 
     */
    public Accession createAccession() {
        return new Accession();
    }

    /**
     * Create an instance of {@link IRISCONVERTGLOBALMESSAGE }
     * 
     */
    public IRISCONVERTGLOBALMESSAGE createIRISCONVERTGLOBALMESSAGE() {
        return new IRISCONVERTGLOBALMESSAGE();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link IRISCCVMESSAGE }
     * 
     */
    public IRISCCVMESSAGE createIRISCCVMESSAGE() {
        return new IRISCCVMESSAGE();
    }

    /**
     * Create an instance of {@link ConcurrentCase }
     * 
     */
    public ConcurrentCase createConcurrentCase() {
        return new ConcurrentCase();
    }

    /**
     * Create an instance of {@link CCVHistoricalAccession }
     * 
     */
    public CCVHistoricalAccession createCCVHistoricalAccession() {
        return new CCVHistoricalAccession();
    }

    /**
     * Create an instance of {@link IRISMODIFYTESTMESSAGE }
     * 
     */
    public IRISMODIFYTESTMESSAGE createIRISMODIFYTESTMESSAGE() {
        return new IRISMODIFYTESTMESSAGE();
    }

    /**
     * Create an instance of {@link IRISORDERSMESSAGE }
     * 
     */
    public IRISORDERSMESSAGE createIRISORDERSMESSAGE() {
        return new IRISORDERSMESSAGE();
    }

    /**
     * Create an instance of {@link IRISPathwaysSlideMessage }
     * 
     */
    public IRISPathwaysSlideMessage createIRISPathwaysSlideMessage() {
        return new IRISPathwaysSlideMessage();
    }

    /**
     * Create an instance of {@link PathwaysSlideStatus }
     * 
     */
    public PathwaysSlideStatus createPathwaysSlideStatus() {
        return new PathwaysSlideStatus();
    }

    /**
     * Create an instance of {@link CaseAssignmentEntity }
     * 
     */
    public CaseAssignmentEntity createCaseAssignmentEntity() {
        return new CaseAssignmentEntity();
    }

    /**
     * Create an instance of {@link CaseAssignments }
     * 
     */
    public CaseAssignments createCaseAssignments() {
        return new CaseAssignments();
    }

    /**
     * Create an instance of {@link IRISREVISETESTMESSAGE }
     * 
     */
    public IRISREVISETESTMESSAGE createIRISREVISETESTMESSAGE() {
        return new IRISREVISETESTMESSAGE();
    }

    /**
     * Create an instance of {@link IRISCCVREVISEMESSAGE }
     * 
     */
    public IRISCCVREVISEMESSAGE createIRISCCVREVISEMESSAGE() {
        return new IRISCCVREVISEMESSAGE();
    }

    /**
     * Create an instance of {@link CCVEvent }
     * 
     */
    public CCVEvent createCCVEvent() {
        return new CCVEvent();
    }

    /**
     * Create an instance of {@link WRAPPER }
     * 
     */
    public WRAPPER createWRAPPER() {
        return new WRAPPER();
    }

    /**
     * Create an instance of {@link IRISVIRTUOSOMESSAGE }
     * 
     */
    public IRISVIRTUOSOMESSAGE createIRISVIRTUOSOMESSAGE() {
        return new IRISVIRTUOSOMESSAGE();
    }

    /**
     * Create an instance of {@link IRISCCVRESULTSMESSAGE }
     * 
     */
    public IRISCCVRESULTSMESSAGE createIRISCCVRESULTSMESSAGE() {
        return new IRISCCVRESULTSMESSAGE();
    }

    /**
     * Create an instance of {@link AccessionSpecimen }
     * 
     */
    public AccessionSpecimen createAccessionSpecimen() {
        return new AccessionSpecimen();
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link CaseLocationEntity }
     * 
     */
    public CaseLocationEntity createCaseLocationEntity() {
        return new CaseLocationEntity();
    }

    /**
     * Create an instance of {@link ReAssignDTO }
     * 
     */
    public ReAssignDTO createReAssignDTO() {
        return new ReAssignDTO();
    }

    /**
     * Create an instance of {@link IRISVANTAGEMESSAGE }
     * 
     */
    public IRISVANTAGEMESSAGE createIRISVANTAGEMESSAGE() {
        return new IRISVANTAGEMESSAGE();
    }

    /**
     * Create an instance of {@link StainerInfo }
     * 
     */
    public StainerInfo createStainerInfo() {
        return new StainerInfo();
    }

    /**
     * Create an instance of {@link IRISRESULTSMESSAGE }
     * 
     */
    public IRISRESULTSMESSAGE createIRISRESULTSMESSAGE() {
        return new IRISRESULTSMESSAGE();
    }

    /**
     * Create an instance of {@link Panel }
     * 
     */
    public Panel createPanel() {
        return new Panel();
    }

    /**
     * Create an instance of {@link TestResultValue }
     * 
     */
    public TestResultValue createTestResultValue() {
        return new TestResultValue();
    }

    /**
     * Create an instance of {@link AttachedPDF }
     * 
     */
    public AttachedPDF createAttachedPDF() {
        return new AttachedPDF();
    }

    /**
     * Create an instance of {@link CCVHistoricalCase }
     * 
     */
    public CCVHistoricalCase createCCVHistoricalCase() {
        return new CCVHistoricalCase();
    }

    /**
     * Create an instance of {@link AccessionText }
     * 
     */
    public AccessionText createAccessionText() {
        return new AccessionText();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Container }
     * 
     */
    public Container createContainer() {
        return new Container();
    }

    /**
     * Create an instance of {@link TestingReportingSiteDetails }
     * 
     */
    public TestingReportingSiteDetails createTestingReportingSiteDetails() {
        return new TestingReportingSiteDetails();
    }

    /**
     * Create an instance of {@link PlaceOfService }
     * 
     */
    public PlaceOfService createPlaceOfService() {
        return new PlaceOfService();
    }

    /**
     * Create an instance of {@link DOB }
     * 
     */
    public DOB createDOB() {
        return new DOB();
    }

    /**
     * Create an instance of {@link ReportHeader }
     * 
     */
    public ReportHeader createReportHeader() {
        return new ReportHeader();
    }

    /**
     * Create an instance of {@link CaseDTO }
     * 
     */
    public CaseDTO createCaseDTO() {
        return new CaseDTO();
    }

    /**
     * Create an instance of {@link PanelResultMarker }
     * 
     */
    public PanelResultMarker createPanelResultMarker() {
        return new PanelResultMarker();
    }

    /**
     * Create an instance of {@link TestResult }
     * 
     */
    public TestResult createTestResult() {
        return new TestResult();
    }

    /**
     * Create an instance of {@link SpecimenTestText }
     * 
     */
    public SpecimenTestText createSpecimenTestText() {
        return new SpecimenTestText();
    }

    /**
     * Create an instance of {@link Block }
     * 
     */
    public Block createBlock() {
        return new Block();
    }

    /**
     * Create an instance of {@link CCVText }
     * 
     */
    public CCVText createCCVText() {
        return new CCVText();
    }

    /**
     * Create an instance of {@link SpecimenResulting }
     * 
     */
    public SpecimenResulting createSpecimenResulting() {
        return new SpecimenResulting();
    }

    /**
     * Create an instance of {@link TestingAndReportingSites }
     * 
     */
    public TestingAndReportingSites createTestingAndReportingSites() {
        return new TestingAndReportingSites();
    }

    /**
     * Create an instance of {@link CaseAssignmentDTO }
     * 
     */
    public CaseAssignmentDTO createCaseAssignmentDTO() {
        return new CaseAssignmentDTO();
    }

    /**
     * Create an instance of {@link PertinentPriorTestResults }
     * 
     */
    public PertinentPriorTestResults createPertinentPriorTestResults() {
        return new PertinentPriorTestResults();
    }

    /**
     * Create an instance of {@link ReagentsUsed }
     * 
     */
    public ReagentsUsed createReagentsUsed() {
        return new ReagentsUsed();
    }

    /**
     * Create an instance of {@link ReportText }
     * 
     */
    public ReportText createReportText() {
        return new ReportText();
    }

    /**
     * Create an instance of {@link SpecimenTest }
     * 
     */
    public SpecimenTest createSpecimenTest() {
        return new SpecimenTest();
    }

    /**
     * Create an instance of {@link ResultTable }
     * 
     */
    public ResultTable createResultTable() {
        return new ResultTable();
    }

    /**
     * Create an instance of {@link Slide }
     * 
     */
    public Slide createSlide() {
        return new Slide();
    }

    /**
     * Create an instance of {@link PlacesOfService }
     * 
     */
    public PlacesOfService createPlacesOfService() {
        return new PlacesOfService();
    }

    /**
     * Create an instance of {@link CCVConcurrentCaseImage }
     * 
     */
    public CCVConcurrentCaseImage createCCVConcurrentCaseImage() {
        return new CCVConcurrentCaseImage();
    }

    /**
     * Create an instance of {@link SerialResults }
     * 
     */
    public SerialResults createSerialResults() {
        return new SerialResults();
    }

    /**
     * Create an instance of {@link ParentContainer }
     * 
     */
    public ParentContainer createParentContainer() {
        return new ParentContainer();
    }

    /**
     * Create an instance of {@link PriorReport }
     * 
     */
    public PriorReport createPriorReport() {
        return new PriorReport();
    }

    /**
     * Create an instance of {@link SpecimenText }
     * 
     */
    public SpecimenText createSpecimenText() {
        return new SpecimenText();
    }

    /**
     * Create an instance of {@link PanelResult }
     * 
     */
    public PanelResult createPanelResult() {
        return new PanelResult();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecimenResulting }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "specimenResulting", scope = AccessionSpecimen.class)
    public JAXBElement<SpecimenResulting> createAccessionSpecimenSpecimenResulting(SpecimenResulting value) {
        return new JAXBElement<SpecimenResulting>(_AccessionSpecimenSpecimenResulting_QNAME, SpecimenResulting.class, AccessionSpecimen.class, value);
    }

}
