//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.30 at 03:09:20 PM IST 
//


package com.lca.ddt.delivery.report.input;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Panel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Panel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="categoryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="labCorpTestCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="legacyTestCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="panelName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceLvlCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="testPerfmdLoc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="techCliaId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="profCliaId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="caseNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="panelResults" type="{http://www.labcorp.com/iris/messages}PanelResult" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reagentsUsed" type="{http://www.labcorp.com/iris/messages}ReagentsUsed" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="anyResults" type="{http://www.labcorp.com/iris/messages}TestResultValue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="templateId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reportSpecimen" type="{http://www.labcorp.com/iris/messages}AccessionSpecimen" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Panel", propOrder = {
    "categoryName",
    "labCorpTestCode",
    "legacyTestCode",
    "panelName",
    "serviceLvlCd",
    "testPerfmdLoc",
    "techCliaId",
    "profCliaId",
    "caseNum",
    "panelResults",
    "reagentsUsed",
    "anyResults",
    "templateId",
    "reportSpecimen"
})
public class Panel {

    protected String categoryName;
    protected String labCorpTestCode;
    protected String legacyTestCode;
    protected String panelName;
    @XmlElement(required = true)
    protected String serviceLvlCd;
    protected String testPerfmdLoc;
    protected String techCliaId;
    protected String profCliaId;
    protected String caseNum;
    protected List<PanelResult> panelResults;
    protected List<ReagentsUsed> reagentsUsed;
    protected List<TestResultValue> anyResults;
    protected String templateId;
    protected List<AccessionSpecimen> reportSpecimen;

    /**
     * Gets the value of the categoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * Sets the value of the categoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryName(String value) {
        this.categoryName = value;
    }

    /**
     * Gets the value of the labCorpTestCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabCorpTestCode() {
        return labCorpTestCode;
    }

    /**
     * Sets the value of the labCorpTestCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabCorpTestCode(String value) {
        this.labCorpTestCode = value;
    }

    /**
     * Gets the value of the legacyTestCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegacyTestCode() {
        return legacyTestCode;
    }

    /**
     * Sets the value of the legacyTestCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegacyTestCode(String value) {
        this.legacyTestCode = value;
    }

    /**
     * Gets the value of the panelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPanelName() {
        return panelName;
    }

    /**
     * Sets the value of the panelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPanelName(String value) {
        this.panelName = value;
    }

    /**
     * Gets the value of the serviceLvlCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceLvlCd() {
        return serviceLvlCd;
    }

    /**
     * Sets the value of the serviceLvlCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceLvlCd(String value) {
        this.serviceLvlCd = value;
    }

    /**
     * Gets the value of the testPerfmdLoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestPerfmdLoc() {
        return testPerfmdLoc;
    }

    /**
     * Sets the value of the testPerfmdLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestPerfmdLoc(String value) {
        this.testPerfmdLoc = value;
    }

    /**
     * Gets the value of the techCliaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechCliaId() {
        return techCliaId;
    }

    /**
     * Sets the value of the techCliaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechCliaId(String value) {
        this.techCliaId = value;
    }

    /**
     * Gets the value of the profCliaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfCliaId() {
        return profCliaId;
    }

    /**
     * Sets the value of the profCliaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfCliaId(String value) {
        this.profCliaId = value;
    }

    /**
     * Gets the value of the caseNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseNum() {
        return caseNum;
    }

    /**
     * Sets the value of the caseNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseNum(String value) {
        this.caseNum = value;
    }

    /**
     * Gets the value of the panelResults property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the panelResults property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPanelResults().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PanelResult }
     * 
     * 
     */
    public List<PanelResult> getPanelResults() {
        if (panelResults == null) {
            panelResults = new ArrayList<PanelResult>();
        }
        return this.panelResults;
    }

    /**
     * Gets the value of the reagentsUsed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reagentsUsed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReagentsUsed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReagentsUsed }
     * 
     * 
     */
    public List<ReagentsUsed> getReagentsUsed() {
        if (reagentsUsed == null) {
            reagentsUsed = new ArrayList<ReagentsUsed>();
        }
        return this.reagentsUsed;
    }

    /**
     * Gets the value of the anyResults property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anyResults property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnyResults().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestResultValue }
     * 
     * 
     */
    public List<TestResultValue> getAnyResults() {
        if (anyResults == null) {
            anyResults = new ArrayList<TestResultValue>();
        }
        return this.anyResults;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * Sets the value of the templateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateId(String value) {
        this.templateId = value;
    }

    /**
     * Gets the value of the reportSpecimen property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportSpecimen property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportSpecimen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccessionSpecimen }
     * 
     * 
     */
    public List<AccessionSpecimen> getReportSpecimen() {
        if (reportSpecimen == null) {
            reportSpecimen = new ArrayList<AccessionSpecimen>();
        }
        return this.reportSpecimen;
    }

}
