//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.30 at 03:09:20 PM IST 
//


package com.lca.ddt.delivery.report.input;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PriorReport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PriorReport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eSignatureComment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="versionNum" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="signedByLoginId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="signedByPrfix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reportStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="signedByLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="signedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="signedLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="signedByAddr" type="{http://www.labcorp.com/iris/messages}Address" minOccurs="0"/>
 *         &lt;element name="revisionReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="revisionCmnts" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PriorReport", propOrder = {
    "eSignatureComment",
    "versionNum",
    "signedByLoginId",
    "signedByPrfix",
    "reportStatus",
    "signedByLine",
    "signedDateTime",
    "signedLocation",
    "signedByAddr",
    "revisionReason",
    "revisionCmnts"
})
public class PriorReport {

    protected String eSignatureComment;
    protected Integer versionNum;
    protected String signedByLoginId;
    protected String signedByPrfix;
    protected String reportStatus;
    protected String signedByLine;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar signedDateTime;
    protected String signedLocation;
    protected Address signedByAddr;
    protected String revisionReason;
    protected String revisionCmnts;

    /**
     * Gets the value of the eSignatureComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getESignatureComment() {
        return eSignatureComment;
    }

    /**
     * Sets the value of the eSignatureComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setESignatureComment(String value) {
        this.eSignatureComment = value;
    }

    /**
     * Gets the value of the versionNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVersionNum() {
        return versionNum;
    }

    /**
     * Sets the value of the versionNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVersionNum(Integer value) {
        this.versionNum = value;
    }

    /**
     * Gets the value of the signedByLoginId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignedByLoginId() {
        return signedByLoginId;
    }

    /**
     * Sets the value of the signedByLoginId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignedByLoginId(String value) {
        this.signedByLoginId = value;
    }

    /**
     * Gets the value of the signedByPrfix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignedByPrfix() {
        return signedByPrfix;
    }

    /**
     * Sets the value of the signedByPrfix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignedByPrfix(String value) {
        this.signedByPrfix = value;
    }

    /**
     * Gets the value of the reportStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportStatus() {
        return reportStatus;
    }

    /**
     * Sets the value of the reportStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportStatus(String value) {
        this.reportStatus = value;
    }

    /**
     * Gets the value of the signedByLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignedByLine() {
        return signedByLine;
    }

    /**
     * Sets the value of the signedByLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignedByLine(String value) {
        this.signedByLine = value;
    }

    /**
     * Gets the value of the signedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSignedDateTime() {
        return signedDateTime;
    }

    /**
     * Sets the value of the signedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSignedDateTime(XMLGregorianCalendar value) {
        this.signedDateTime = value;
    }

    /**
     * Gets the value of the signedLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignedLocation() {
        return signedLocation;
    }

    /**
     * Sets the value of the signedLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignedLocation(String value) {
        this.signedLocation = value;
    }

    /**
     * Gets the value of the signedByAddr property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getSignedByAddr() {
        return signedByAddr;
    }

    /**
     * Sets the value of the signedByAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setSignedByAddr(Address value) {
        this.signedByAddr = value;
    }

    /**
     * Gets the value of the revisionReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevisionReason() {
        return revisionReason;
    }

    /**
     * Sets the value of the revisionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevisionReason(String value) {
        this.revisionReason = value;
    }

    /**
     * Gets the value of the revisionCmnts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevisionCmnts() {
        return revisionCmnts;
    }

    /**
     * Sets the value of the revisionCmnts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevisionCmnts(String value) {
        this.revisionCmnts = value;
    }

}
