//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.30 at 03:09:20 PM IST 
//


package com.lca.ddt.delivery.report.input;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Report complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Report">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="templateId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reportTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reportType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="versionNum" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="signedByLoginId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="signedByPrfix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reportStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="signedByLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="licenseNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="signedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="medicalDirDegree" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="medicalDirFName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="medicalDirLName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="medicalDirLogin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="signedLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="labInfoSystemCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mdCliaNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mdAddr" type="{http://www.labcorp.com/iris/messages}Address" minOccurs="0"/>
 *         &lt;element name="signedByAddr" type="{http://www.labcorp.com/iris/messages}Address" minOccurs="0"/>
 *         &lt;element name="eSignatureComment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reportImages" type="{http://www.labcorp.com/iris/messages}Image" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reportTexts" type="{http://www.labcorp.com/iris/messages}ReportText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reportHeader" type="{http://www.labcorp.com/iris/messages}ReportHeader" minOccurs="0"/>
 *         &lt;element name="priorReports" type="{http://www.labcorp.com/iris/messages}PriorReport" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pertinentPriorTestResults" type="{http://www.labcorp.com/iris/messages}PertinentPriorTestResults" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="serialResults" type="{http://www.labcorp.com/iris/messages}SerialResults" minOccurs="0"/>
 *         &lt;element name="testingAndReportingSites" type="{http://www.labcorp.com/iris/messages}TestingAndReportingSites" minOccurs="0"/>
 *         &lt;element name="placesOfService" type="{http://www.labcorp.com/iris/messages}PlacesOfService" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Report", propOrder = {
    "templateId",
    "reportTitle",
    "reportType",
    "versionNum",
    "signedByLoginId",
    "signedByPrfix",
    "reportStatus",
    "signedByLine",
    "licenseNum",
    "signedDateTime",
    "medicalDirDegree",
    "medicalDirFName",
    "medicalDirLName",
    "medicalDirLogin",
    "signedLocation",
    "labInfoSystemCd",
    "mdCliaNum",
    "mdAddr",
    "signedByAddr",
    "eSignatureComment",
    "reportImages",
    "reportTexts",
    "reportHeader",
    "priorReports",
    "pertinentPriorTestResults",
    "serialResults",
    "testingAndReportingSites",
    "placesOfService"
})
public class Report {

    protected String templateId;
    protected String reportTitle;
    protected String reportType;
    protected Integer versionNum;
    protected String signedByLoginId;
    protected String signedByPrfix;
    protected String reportStatus;
    protected String signedByLine;
    protected String licenseNum;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar signedDateTime;
    protected String medicalDirDegree;
    protected String medicalDirFName;
    protected String medicalDirLName;
    protected String medicalDirLogin;
    protected String signedLocation;
    protected String labInfoSystemCd;
    protected String mdCliaNum;
    protected Address mdAddr;
    protected Address signedByAddr;
    protected String eSignatureComment;
    protected List<Image> reportImages;
    protected List<ReportText> reportTexts;
    protected ReportHeader reportHeader;
    protected List<PriorReport> priorReports;
    protected List<PertinentPriorTestResults> pertinentPriorTestResults;
    protected SerialResults serialResults;
    protected TestingAndReportingSites testingAndReportingSites;
    protected PlacesOfService placesOfService;

    /**
     * Gets the value of the templateId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * Sets the value of the templateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateId(String value) {
        this.templateId = value;
    }

    /**
     * Gets the value of the reportTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportTitle() {
        return reportTitle;
    }

    /**
     * Sets the value of the reportTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportTitle(String value) {
        this.reportTitle = value;
    }

    /**
     * Gets the value of the reportType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportType() {
        return reportType;
    }

    /**
     * Sets the value of the reportType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportType(String value) {
        this.reportType = value;
    }

    /**
     * Gets the value of the versionNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVersionNum() {
        return versionNum;
    }

    /**
     * Sets the value of the versionNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVersionNum(Integer value) {
        this.versionNum = value;
    }

    /**
     * Gets the value of the signedByLoginId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignedByLoginId() {
        return signedByLoginId;
    }

    /**
     * Sets the value of the signedByLoginId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignedByLoginId(String value) {
        this.signedByLoginId = value;
    }

    /**
     * Gets the value of the signedByPrfix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignedByPrfix() {
        return signedByPrfix;
    }

    /**
     * Sets the value of the signedByPrfix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignedByPrfix(String value) {
        this.signedByPrfix = value;
    }

    /**
     * Gets the value of the reportStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportStatus() {
        return reportStatus;
    }

    /**
     * Sets the value of the reportStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportStatus(String value) {
        this.reportStatus = value;
    }

    /**
     * Gets the value of the signedByLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignedByLine() {
        return signedByLine;
    }

    /**
     * Sets the value of the signedByLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignedByLine(String value) {
        this.signedByLine = value;
    }

    /**
     * Gets the value of the licenseNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseNum() {
        return licenseNum;
    }

    /**
     * Sets the value of the licenseNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseNum(String value) {
        this.licenseNum = value;
    }

    /**
     * Gets the value of the signedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSignedDateTime() {
        return signedDateTime;
    }

    /**
     * Sets the value of the signedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSignedDateTime(XMLGregorianCalendar value) {
        this.signedDateTime = value;
    }

    /**
     * Gets the value of the medicalDirDegree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicalDirDegree() {
        return medicalDirDegree;
    }

    /**
     * Sets the value of the medicalDirDegree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicalDirDegree(String value) {
        this.medicalDirDegree = value;
    }

    /**
     * Gets the value of the medicalDirFName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicalDirFName() {
        return medicalDirFName;
    }

    /**
     * Sets the value of the medicalDirFName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicalDirFName(String value) {
        this.medicalDirFName = value;
    }

    /**
     * Gets the value of the medicalDirLName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicalDirLName() {
        return medicalDirLName;
    }

    /**
     * Sets the value of the medicalDirLName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicalDirLName(String value) {
        this.medicalDirLName = value;
    }

    /**
     * Gets the value of the medicalDirLogin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicalDirLogin() {
        return medicalDirLogin;
    }

    /**
     * Sets the value of the medicalDirLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicalDirLogin(String value) {
        this.medicalDirLogin = value;
    }

    /**
     * Gets the value of the signedLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignedLocation() {
        return signedLocation;
    }

    /**
     * Sets the value of the signedLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignedLocation(String value) {
        this.signedLocation = value;
    }

    /**
     * Gets the value of the labInfoSystemCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabInfoSystemCd() {
        return labInfoSystemCd;
    }

    /**
     * Sets the value of the labInfoSystemCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabInfoSystemCd(String value) {
        this.labInfoSystemCd = value;
    }

    /**
     * Gets the value of the mdCliaNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdCliaNum() {
        return mdCliaNum;
    }

    /**
     * Sets the value of the mdCliaNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdCliaNum(String value) {
        this.mdCliaNum = value;
    }

    /**
     * Gets the value of the mdAddr property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getMdAddr() {
        return mdAddr;
    }

    /**
     * Sets the value of the mdAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setMdAddr(Address value) {
        this.mdAddr = value;
    }

    /**
     * Gets the value of the signedByAddr property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getSignedByAddr() {
        return signedByAddr;
    }

    /**
     * Sets the value of the signedByAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setSignedByAddr(Address value) {
        this.signedByAddr = value;
    }

    /**
     * Gets the value of the eSignatureComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getESignatureComment() {
        return eSignatureComment;
    }

    /**
     * Sets the value of the eSignatureComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setESignatureComment(String value) {
        this.eSignatureComment = value;
    }

    /**
     * Gets the value of the reportImages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportImages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportImages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Image }
     * 
     * 
     */
    public List<Image> getReportImages() {
        if (reportImages == null) {
            reportImages = new ArrayList<Image>();
        }
        return this.reportImages;
    }

    /**
     * Gets the value of the reportTexts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportTexts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportTexts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReportText }
     * 
     * 
     */
    public List<ReportText> getReportTexts() {
        if (reportTexts == null) {
            reportTexts = new ArrayList<ReportText>();
        }
        return this.reportTexts;
    }

    /**
     * Gets the value of the reportHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ReportHeader }
     *     
     */
    public ReportHeader getReportHeader() {
        return reportHeader;
    }

    /**
     * Sets the value of the reportHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportHeader }
     *     
     */
    public void setReportHeader(ReportHeader value) {
        this.reportHeader = value;
    }

    /**
     * Gets the value of the priorReports property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priorReports property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPriorReports().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PriorReport }
     * 
     * 
     */
    public List<PriorReport> getPriorReports() {
        if (priorReports == null) {
            priorReports = new ArrayList<PriorReport>();
        }
        return this.priorReports;
    }

    /**
     * Gets the value of the pertinentPriorTestResults property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pertinentPriorTestResults property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPertinentPriorTestResults().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PertinentPriorTestResults }
     * 
     * 
     */
    public List<PertinentPriorTestResults> getPertinentPriorTestResults() {
        if (pertinentPriorTestResults == null) {
            pertinentPriorTestResults = new ArrayList<PertinentPriorTestResults>();
        }
        return this.pertinentPriorTestResults;
    }

    /**
     * Gets the value of the serialResults property.
     * 
     * @return
     *     possible object is
     *     {@link SerialResults }
     *     
     */
    public SerialResults getSerialResults() {
        return serialResults;
    }

    /**
     * Sets the value of the serialResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link SerialResults }
     *     
     */
    public void setSerialResults(SerialResults value) {
        this.serialResults = value;
    }

    /**
     * Gets the value of the testingAndReportingSites property.
     * 
     * @return
     *     possible object is
     *     {@link TestingAndReportingSites }
     *     
     */
    public TestingAndReportingSites getTestingAndReportingSites() {
        return testingAndReportingSites;
    }

    /**
     * Sets the value of the testingAndReportingSites property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestingAndReportingSites }
     *     
     */
    public void setTestingAndReportingSites(TestingAndReportingSites value) {
        this.testingAndReportingSites = value;
    }

    /**
     * Gets the value of the placesOfService property.
     * 
     * @return
     *     possible object is
     *     {@link PlacesOfService }
     *     
     */
    public PlacesOfService getPlacesOfService() {
        return placesOfService;
    }

    /**
     * Sets the value of the placesOfService property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlacesOfService }
     *     
     */
    public void setPlacesOfService(PlacesOfService value) {
        this.placesOfService = value;
    }

}
