//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.30 at 03:09:20 PM IST 
//


package com.lca.ddt.delivery.report.input;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ReportHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="controlId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accessionedBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accessionTmstp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="serviceTmstp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="accessionedLoc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="npi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountAddr" type="{http://www.labcorp.com/iris/messages}Address" minOccurs="0"/>
 *         &lt;element name="accountFax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderingPhyDegree" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderingPhyFName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderingPhyMName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderingPhyLName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderingPhyPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="referPhyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="referPhyNPI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="salesRepName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="regionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="territoryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pDob" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="pAge" type="{http://www.labcorp.com/iris/messages}DOB" minOccurs="0"/>
 *         &lt;element name="pGender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MRN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pMiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lpid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pSSN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pAddr" type="{http://www.labcorp.com/iris/messages}Address" minOccurs="0"/>
 *         &lt;element name="perfLabAddr" type="{http://www.labcorp.com/iris/messages}Address" minOccurs="0"/>
 *         &lt;element name="physicianId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mpid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportHeader", propOrder = {
    "controlId",
    "accessionedBy",
    "accessionTmstp",
    "serviceTmstp",
    "accessionedLoc",
    "npi",
    "accountName",
    "accountNum",
    "accountPhone",
    "accountAddr",
    "accountFax",
    "orderingPhyDegree",
    "orderingPhyFName",
    "orderingPhyMName",
    "orderingPhyLName",
    "orderingPhyPhone",
    "referPhyName",
    "referPhyNPI",
    "salesRepName",
    "regionName",
    "territoryName",
    "pDob",
    "pAge",
    "pGender",
    "mrn",
    "pFirstName",
    "pMiddleName",
    "pLastName",
    "pPhone",
    "lpid",
    "pssn",
    "pAddr",
    "perfLabAddr",
    "physicianId",
    "mpid"
})
public class ReportHeader {

    protected String controlId;
    @XmlElement(required = true)
    protected String accessionedBy;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar accessionTmstp;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar serviceTmstp;
    protected String accessionedLoc;
    protected String npi;
    protected String accountName;
    protected String accountNum;
    protected String accountPhone;
    protected Address accountAddr;
    protected String accountFax;
    protected String orderingPhyDegree;
    protected String orderingPhyFName;
    protected String orderingPhyMName;
    protected String orderingPhyLName;
    protected String orderingPhyPhone;
    protected String referPhyName;
    protected String referPhyNPI;
    protected String salesRepName;
    protected String regionName;
    protected String territoryName;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar pDob;
    protected DOB pAge;
    protected String pGender;
    @XmlElement(name = "MRN")
    protected String mrn;
    protected String pFirstName;
    protected String pMiddleName;
    protected String pLastName;
    protected String pPhone;
    protected String lpid;
    @XmlElement(name = "pSSN")
    protected String pssn;
    protected Address pAddr;
    protected Address perfLabAddr;
    protected String physicianId;
    protected String mpid;

    /**
     * Gets the value of the controlId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlId() {
        return controlId;
    }

    /**
     * Sets the value of the controlId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlId(String value) {
        this.controlId = value;
    }

    /**
     * Gets the value of the accessionedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessionedBy() {
        return accessionedBy;
    }

    /**
     * Sets the value of the accessionedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessionedBy(String value) {
        this.accessionedBy = value;
    }

    /**
     * Gets the value of the accessionTmstp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAccessionTmstp() {
        return accessionTmstp;
    }

    /**
     * Sets the value of the accessionTmstp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAccessionTmstp(XMLGregorianCalendar value) {
        this.accessionTmstp = value;
    }

    /**
     * Gets the value of the serviceTmstp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getServiceTmstp() {
        return serviceTmstp;
    }

    /**
     * Sets the value of the serviceTmstp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setServiceTmstp(XMLGregorianCalendar value) {
        this.serviceTmstp = value;
    }

    /**
     * Gets the value of the accessionedLoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessionedLoc() {
        return accessionedLoc;
    }

    /**
     * Sets the value of the accessionedLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessionedLoc(String value) {
        this.accessionedLoc = value;
    }

    /**
     * Gets the value of the npi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpi() {
        return npi;
    }

    /**
     * Sets the value of the npi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpi(String value) {
        this.npi = value;
    }

    /**
     * Gets the value of the accountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * Sets the value of the accountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountName(String value) {
        this.accountName = value;
    }

    /**
     * Gets the value of the accountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNum() {
        return accountNum;
    }

    /**
     * Sets the value of the accountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNum(String value) {
        this.accountNum = value;
    }

    /**
     * Gets the value of the accountPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountPhone() {
        return accountPhone;
    }

    /**
     * Sets the value of the accountPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountPhone(String value) {
        this.accountPhone = value;
    }

    /**
     * Gets the value of the accountAddr property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAccountAddr() {
        return accountAddr;
    }

    /**
     * Sets the value of the accountAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAccountAddr(Address value) {
        this.accountAddr = value;
    }

    /**
     * Gets the value of the accountFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountFax() {
        return accountFax;
    }

    /**
     * Sets the value of the accountFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountFax(String value) {
        this.accountFax = value;
    }

    /**
     * Gets the value of the orderingPhyDegree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderingPhyDegree() {
        return orderingPhyDegree;
    }

    /**
     * Sets the value of the orderingPhyDegree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderingPhyDegree(String value) {
        this.orderingPhyDegree = value;
    }

    /**
     * Gets the value of the orderingPhyFName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderingPhyFName() {
        return orderingPhyFName;
    }

    /**
     * Sets the value of the orderingPhyFName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderingPhyFName(String value) {
        this.orderingPhyFName = value;
    }

    /**
     * Gets the value of the orderingPhyMName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderingPhyMName() {
        return orderingPhyMName;
    }

    /**
     * Sets the value of the orderingPhyMName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderingPhyMName(String value) {
        this.orderingPhyMName = value;
    }

    /**
     * Gets the value of the orderingPhyLName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderingPhyLName() {
        return orderingPhyLName;
    }

    /**
     * Sets the value of the orderingPhyLName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderingPhyLName(String value) {
        this.orderingPhyLName = value;
    }

    /**
     * Gets the value of the orderingPhyPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderingPhyPhone() {
        return orderingPhyPhone;
    }

    /**
     * Sets the value of the orderingPhyPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderingPhyPhone(String value) {
        this.orderingPhyPhone = value;
    }

    /**
     * Gets the value of the referPhyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferPhyName() {
        return referPhyName;
    }

    /**
     * Sets the value of the referPhyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferPhyName(String value) {
        this.referPhyName = value;
    }

    /**
     * Gets the value of the referPhyNPI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferPhyNPI() {
        return referPhyNPI;
    }

    /**
     * Sets the value of the referPhyNPI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferPhyNPI(String value) {
        this.referPhyNPI = value;
    }

    /**
     * Gets the value of the salesRepName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesRepName() {
        return salesRepName;
    }

    /**
     * Sets the value of the salesRepName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesRepName(String value) {
        this.salesRepName = value;
    }

    /**
     * Gets the value of the regionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * Sets the value of the regionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionName(String value) {
        this.regionName = value;
    }

    /**
     * Gets the value of the territoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerritoryName() {
        return territoryName;
    }

    /**
     * Sets the value of the territoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerritoryName(String value) {
        this.territoryName = value;
    }

    /**
     * Gets the value of the pDob property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPDob() {
        return pDob;
    }

    /**
     * Sets the value of the pDob property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPDob(XMLGregorianCalendar value) {
        this.pDob = value;
    }

    /**
     * Gets the value of the pAge property.
     * 
     * @return
     *     possible object is
     *     {@link DOB }
     *     
     */
    public DOB getPAge() {
        return pAge;
    }

    /**
     * Sets the value of the pAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOB }
     *     
     */
    public void setPAge(DOB value) {
        this.pAge = value;
    }

    /**
     * Gets the value of the pGender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPGender() {
        return pGender;
    }

    /**
     * Sets the value of the pGender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPGender(String value) {
        this.pGender = value;
    }

    /**
     * Gets the value of the mrn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMRN() {
        return mrn;
    }

    /**
     * Sets the value of the mrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMRN(String value) {
        this.mrn = value;
    }

    /**
     * Gets the value of the pFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPFirstName() {
        return pFirstName;
    }

    /**
     * Sets the value of the pFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPFirstName(String value) {
        this.pFirstName = value;
    }

    /**
     * Gets the value of the pMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPMiddleName() {
        return pMiddleName;
    }

    /**
     * Sets the value of the pMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPMiddleName(String value) {
        this.pMiddleName = value;
    }

    /**
     * Gets the value of the pLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPLastName() {
        return pLastName;
    }

    /**
     * Sets the value of the pLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPLastName(String value) {
        this.pLastName = value;
    }

    /**
     * Gets the value of the pPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPPhone() {
        return pPhone;
    }

    /**
     * Sets the value of the pPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPPhone(String value) {
        this.pPhone = value;
    }

    /**
     * Gets the value of the lpid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLpid() {
        return lpid;
    }

    /**
     * Sets the value of the lpid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLpid(String value) {
        this.lpid = value;
    }

    /**
     * Gets the value of the pssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPSSN() {
        return pssn;
    }

    /**
     * Sets the value of the pssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPSSN(String value) {
        this.pssn = value;
    }

    /**
     * Gets the value of the pAddr property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getPAddr() {
        return pAddr;
    }

    /**
     * Sets the value of the pAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setPAddr(Address value) {
        this.pAddr = value;
    }

    /**
     * Gets the value of the perfLabAddr property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getPerfLabAddr() {
        return perfLabAddr;
    }

    /**
     * Sets the value of the perfLabAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setPerfLabAddr(Address value) {
        this.perfLabAddr = value;
    }

    /**
     * Gets the value of the physicianId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicianId() {
        return physicianId;
    }

    /**
     * Sets the value of the physicianId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicianId(String value) {
        this.physicianId = value;
    }

    /**
     * Gets the value of the mpid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMpid() {
        return mpid;
    }

    /**
     * Sets the value of the mpid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMpid(String value) {
        this.mpid = value;
    }

}
