//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.30 at 03:09:20 PM IST 
//


package com.lca.ddt.delivery.report.input;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SerialResults complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SerialResults">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="graphImage" type="{http://www.labcorp.com/iris/messages}Image" minOccurs="0"/>
 *         &lt;element name="resultsTable" type="{http://www.labcorp.com/iris/messages}ResultTable" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SerialResults", propOrder = {
    "graphImage",
    "resultsTable"
})
public class SerialResults {

    protected Image graphImage;
    protected List<ResultTable> resultsTable;

    /**
     * Gets the value of the graphImage property.
     * 
     * @return
     *     possible object is
     *     {@link Image }
     *     
     */
    public Image getGraphImage() {
        return graphImage;
    }

    /**
     * Sets the value of the graphImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Image }
     *     
     */
    public void setGraphImage(Image value) {
        this.graphImage = value;
    }

    /**
     * Gets the value of the resultsTable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resultsTable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResultsTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResultTable }
     * 
     * 
     */
    public List<ResultTable> getResultsTable() {
        if (resultsTable == null) {
            resultsTable = new ArrayList<ResultTable>();
        }
        return this.resultsTable;
    }

}
