//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.30 at 03:09:20 PM IST 
//


package com.lca.ddt.delivery.report.input;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SpecimenResulting complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecimenResulting">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="specimenId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prepTubeId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="prepCellCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="prepSpecVolume" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="stainingTubeId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="stainingCellCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="stainingSpecVolume" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="prepDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="stainingDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="onInstrumentDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="readyForAnalysisDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="analysisCompletionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="assignedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="repeatOrRestainDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="importedActivePDFDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecimenResulting", propOrder = {
    "specimenId",
    "prepTubeId",
    "prepCellCount",
    "prepSpecVolume",
    "stainingTubeId",
    "stainingCellCount",
    "stainingSpecVolume",
    "prepDate",
    "stainingDate",
    "onInstrumentDate",
    "readyForAnalysisDate",
    "analysisCompletionDate",
    "assignedDate",
    "repeatOrRestainDate",
    "importedActivePDFDate"
})
public class SpecimenResulting {

    @XmlElement(required = true)
    protected String specimenId;
    protected Integer prepTubeId;
    protected Integer prepCellCount;
    protected Integer prepSpecVolume;
    protected Integer stainingTubeId;
    protected Integer stainingCellCount;
    protected Integer stainingSpecVolume;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar prepDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar stainingDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar onInstrumentDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar readyForAnalysisDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar analysisCompletionDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar assignedDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar repeatOrRestainDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar importedActivePDFDate;

    /**
     * Gets the value of the specimenId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecimenId() {
        return specimenId;
    }

    /**
     * Sets the value of the specimenId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecimenId(String value) {
        this.specimenId = value;
    }

    /**
     * Gets the value of the prepTubeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPrepTubeId() {
        return prepTubeId;
    }

    /**
     * Sets the value of the prepTubeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPrepTubeId(Integer value) {
        this.prepTubeId = value;
    }

    /**
     * Gets the value of the prepCellCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPrepCellCount() {
        return prepCellCount;
    }

    /**
     * Sets the value of the prepCellCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPrepCellCount(Integer value) {
        this.prepCellCount = value;
    }

    /**
     * Gets the value of the prepSpecVolume property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPrepSpecVolume() {
        return prepSpecVolume;
    }

    /**
     * Sets the value of the prepSpecVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPrepSpecVolume(Integer value) {
        this.prepSpecVolume = value;
    }

    /**
     * Gets the value of the stainingTubeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStainingTubeId() {
        return stainingTubeId;
    }

    /**
     * Sets the value of the stainingTubeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStainingTubeId(Integer value) {
        this.stainingTubeId = value;
    }

    /**
     * Gets the value of the stainingCellCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStainingCellCount() {
        return stainingCellCount;
    }

    /**
     * Sets the value of the stainingCellCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStainingCellCount(Integer value) {
        this.stainingCellCount = value;
    }

    /**
     * Gets the value of the stainingSpecVolume property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStainingSpecVolume() {
        return stainingSpecVolume;
    }

    /**
     * Sets the value of the stainingSpecVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStainingSpecVolume(Integer value) {
        this.stainingSpecVolume = value;
    }

    /**
     * Gets the value of the prepDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPrepDate() {
        return prepDate;
    }

    /**
     * Sets the value of the prepDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPrepDate(XMLGregorianCalendar value) {
        this.prepDate = value;
    }

    /**
     * Gets the value of the stainingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStainingDate() {
        return stainingDate;
    }

    /**
     * Sets the value of the stainingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStainingDate(XMLGregorianCalendar value) {
        this.stainingDate = value;
    }

    /**
     * Gets the value of the onInstrumentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOnInstrumentDate() {
        return onInstrumentDate;
    }

    /**
     * Sets the value of the onInstrumentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOnInstrumentDate(XMLGregorianCalendar value) {
        this.onInstrumentDate = value;
    }

    /**
     * Gets the value of the readyForAnalysisDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReadyForAnalysisDate() {
        return readyForAnalysisDate;
    }

    /**
     * Sets the value of the readyForAnalysisDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReadyForAnalysisDate(XMLGregorianCalendar value) {
        this.readyForAnalysisDate = value;
    }

    /**
     * Gets the value of the analysisCompletionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAnalysisCompletionDate() {
        return analysisCompletionDate;
    }

    /**
     * Sets the value of the analysisCompletionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAnalysisCompletionDate(XMLGregorianCalendar value) {
        this.analysisCompletionDate = value;
    }

    /**
     * Gets the value of the assignedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAssignedDate() {
        return assignedDate;
    }

    /**
     * Sets the value of the assignedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAssignedDate(XMLGregorianCalendar value) {
        this.assignedDate = value;
    }

    /**
     * Gets the value of the repeatOrRestainDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRepeatOrRestainDate() {
        return repeatOrRestainDate;
    }

    /**
     * Sets the value of the repeatOrRestainDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRepeatOrRestainDate(XMLGregorianCalendar value) {
        this.repeatOrRestainDate = value;
    }

    /**
     * Gets the value of the importedActivePDFDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getImportedActivePDFDate() {
        return importedActivePDFDate;
    }

    /**
     * Sets the value of the importedActivePDFDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setImportedActivePDFDate(XMLGregorianCalendar value) {
        this.importedActivePDFDate = value;
    }

}
