//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.30 at 03:09:20 PM IST 
//


package com.lca.ddt.delivery.report.input;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestingAndReportingSites complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestingAndReportingSites">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="professionalComponent" type="{http://www.labcorp.com/iris/messages}TestingReportingSiteDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="technicalComponent" type="{http://www.labcorp.com/iris/messages}TestingReportingSiteDetails" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestingAndReportingSites", propOrder = {
    "professionalComponent",
    "technicalComponent"
})
public class TestingAndReportingSites {

    protected List<TestingReportingSiteDetails> professionalComponent;
    protected List<TestingReportingSiteDetails> technicalComponent;

    /**
     * Gets the value of the professionalComponent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the professionalComponent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfessionalComponent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestingReportingSiteDetails }
     * 
     * 
     */
    public List<TestingReportingSiteDetails> getProfessionalComponent() {
        if (professionalComponent == null) {
            professionalComponent = new ArrayList<TestingReportingSiteDetails>();
        }
        return this.professionalComponent;
    }

    /**
     * Gets the value of the technicalComponent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the technicalComponent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechnicalComponent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestingReportingSiteDetails }
     * 
     * 
     */
    public List<TestingReportingSiteDetails> getTechnicalComponent() {
        if (technicalComponent == null) {
            technicalComponent = new ArrayList<TestingReportingSiteDetails>();
        }
        return this.technicalComponent;
    }

}
